### ISSUE TITLE
EMC 4.0 erstellt keine cut-Datei mehr!

### ISSUE THREAD

**Issue by Helmut1962** [betonme/e2openplugin-EnhancedMovieCenter#122]
Hallo Leute,

auf einen Hinweis im OpenPli Forum poste ich mein Problem auch hier, ich hoffe es wird auch in deutsch verstanden.

Ich verwende OpenPli4 und EMC 4.0 auf meiner Xtrend 9200 bereits seit einiger Zeit und hatte nie ein Problem, seit kurzem aber werden die Cut-Dateien von EMC nur mehr im Hauptordner (hdd/movie) korrekt erstellt in allen anderen Ordnern egal ob auf der selben internen Festplatte oder bei Filmen auf externen Festplatten werden beim Start der Wiedergabe zwar eine Cut-Datei erstellt, aber kein Eintrag hineingeschrieben, vermutlich daher wird beim Stoppen des Filmes diese Cut-Datei wieder gelöscht, Daher habe ich außer im Hauptordner keine Fortschrittsanzeige mehr.

Kann jemand den Fehler nachbilden bzw. hat jemand einen Rat zur Abhilfe?

Gruß
Helmut

**Comment by betonme** [comment]
Hallo,

bei mir werden Cut Dateien auch in Unterordner angelegt.

NFS habe ich nicht im Einsatz.

Ein EMC oder E2 Log wäre hilfreich.
Im EMC Setup kann man Debug Ausgaben ausgeben und mitloggen lassen.

Mit Telnet die Ausgaben des folgenden Befehls sind auch Interessant:
mount

**Comment by Swiss-MAD** [comment]
Ich verwende an der DM800se ausschliesslich eine Netzwerkplatte.
Jedoch über cifs (Samba) und habe keinerlei Probleme, auch in Unterverzeichnissen nicht.
Ich vermute ein Problem mit den Einstellungen des NAS.

I am using on my DM800se only a NAS drive mounted with cifs (Samba), and have no problems.
I think it's a problem with the config of the NAS drive.
Do yo try to mount with cifs ?

**Comment by koivo** [comment]
Die Cuts werden irgendwie nur sporadisch erstellt. Ich konnte kein Muster erkennen.
Mit einer älteren Version 3.7 Beta funktioniert das problemlos auf den selben Mounts und Freigaben.
Wenn aber mal ein Cuts erstellt wurde, dann gehen auch die Updates des Cuts.
Ich habe mal einen Debug Log erstellt: http://pastebin.com/jurF1J8S
Vielleicht hilft das.

**Comment by dhwz** [comment]
Welche Box ist das? Nach deinem Log ist das eine DreamOS Box, danach ist das kein Fehler von EMC, sondern ein bekannter Bug.

**Comment by koivo** [comment]
Es handelt sich um eine AX 51HD. Ich hab aber das gleiche Problem auf der ET10000.
Bei uns im Forum betrifft es auch andere die aber alle keine Dreambox haben.
Auf der lokalen Festplatte unter /movie werden aber .cuts erstellt und geändert.

**Comment by dhwz** [comment]
please reopen a new issue if this is still relevant
