### ISSUE TITLE
Eit file show wrong languish

### ISSUE THREAD

**Issue by Seth72** [betonme/e2openplugin-EnhancedMovieCenter#132]
Hello i have a problem with enhanced 3.74 in newest blackhole and in my eit file from recorded movie i have finnish norvegian and swedish and i only want to show swedish information about the movie .
I have older enhanced 1.1.0 and that show the correct languish .
Can this be fixes
Regards seth

**Comment by betonme** [comment]
Hello Seth72,

can You upload a sample set of files?
EIT and META

**Comment by Seth72** [comment]
I cant upload it here. How can i sen them to you

Regards seth

**Comment by betonme** [comment]
You can just drag and drop it here. Maybe You have to zip it before. 

Do You have any account at an E2 forum like openatv, ihad...?

**Comment by Seth72** [comment]
Den 3 nov 2015 22:16 skrev "Frank Glaser" <notifications@github.com>:

**Comment by Seth72** [comment]
hello i wounder if you got the files

regards Seth

**Comment by betonme** [comment]
No, I didn't get anything. I also checked my spam folder.

**Comment by Seth72** [comment]
now i emaild them again on glaserfrank@gmail.com

regards Seth

**Comment by Seth72** [comment]
i hope you find whats wrong like this plugin.
regards seth

**Comment by betonme** [comment]
We close this here and open a new request to make the ifo support optinal or with language support.

**Comment by hd75hd** [comment]
Sorry for my english ..

with this commit, we dont see the description of some german records

http://www.opena.tv/plugins/20405-emc-zeigt-keine-filminhaltsinfo-mehr.html#post183398

i print this
print ISO_639_language_code
print lang
sometimes it is
14:00:28.938 {   } Plugins/Extensions/EnhancedMovieCenter/EitSupport.py:271 __readEitFile EU
14:00:28.939 {   } Plugins/Extensions/EnhancedMovieCenter/EitSupport.py:272 __readEitFile deu
and 
14:00:31.729 {   } Plugins/Extensions/EnhancedMovieCenter/EitSupport.py:271 __readEitFile eu
14:00:31.729 {   } Plugins/Extensions/EnhancedMovieCenter/EitSupport.py:272 __readEitFile deu
14:00:31.729 {   } Plugins/Extensions/EnhancedMovieCenter/EitSupport.py:271 __readEitFile eu
14:00:31.729 {   } Plugins/Extensions/EnhancedMovieCenter/EitSupport.py:272 __readEitFile deu
14:00:31.730 {   } Plugins/Extensions/EnhancedMovieCenter/EitSupport.py:279 __readEitFile de
14:00:31.730 {   } Plugins/Extensions/EnhancedMovieCenter/EitSupport.py:280 __readEitFile deu
14:00:31.730 {   } Plugins/Extensions/EnhancedMovieCenter/EitSupport.py:279 __readEitFile de
14:00:31.731 {   } Plugins/Extensions/EnhancedMovieCenter/EitSupport.py:280 __readEitFile deu

if i reverse it, i see all description of the records

**Comment by betonme** [comment]
Have You tested the newer one be7362ac4cbde267f01a604c846cb1c1807d07a6

**Comment by Seth72** [comment]
hello , are the a new file

2015-11-08 14:20 GMT+01:00 Frank Glaser <notifications@github.com>:

**Comment by betonme** [comment]
Sorry, what do You mean?

This be7362ac4cbde267f01a604c846cb1c1807d07a6 is newer than the f97628cc391223228cd7896f251c121dc338684b

**Comment by Seth72** [comment]
got mail from you
"Frank Glaser
Have You tested the newer one be7362a
14:20 (10 minuter sedan)
Have You tested the newer one be7362a

2015-11-08 14:23 GMT+01:00 Frank Glaser <notifications@github.com>:

**Comment by betonme** [comment]
@Seth72 Sorry, it is not related to Your problem.
It is reagrding the mentioned problem of @hd75hd

**Comment by hd75hd** [comment]
i made a new test with the last version of it ..

https://github.com/betonme/e2openplugin-EnhancedMovieCenter/commit/d552d6333ddce00659ecb975e00415c1d2ae5f82

the same results 

14:37:30.018 {   } Plugins/Extensions/EnhancedMovieCenter/EitSupport.py:272 __readEitFile EU
14:37:30.019 {   } Plugins/Extensions/EnhancedMovieCenter/EitSupport.py:273 __readEitFile deu
14:37:30.019 {   } Plugins/Extensions/EnhancedMovieCenter/EitSupport.py:272 __readEitFile EU
14:37:30.019 {   } Plugins/Extensions/EnhancedMovieCenter/EitSupport.py:273 __readEitFile deu
14:37:30.020 {   } Plugins/Extensions/EnhancedMovieCenter/EitSupport.py:280 __readEitFile DE
14:37:30.020 {   } Plugins/Extensions/EnhancedMovieCenter/EitSupport.py:281 __readEitFile deu
14:37:30.020 {   } Plugins/Extensions/EnhancedMovieCenter/EitSupport.py:280 __readEitFile DE
14:37:30.020 {   } Plugins/Extensions/EnhancedMovieCenter/EitSupport.py:281 __readEitFile deu
14:37:30.021 {   } Plugins/Extensions/EnhancedMovieCenter/EitSupport.py:280 __readEitFile DE
14:37:30.021 {   } Plugins/Extensions/EnhancedMovieCenter/EitSupport.py:281 __readEitFile deu
14:37:30.021 {   } Plugins/Extensions/EnhancedMovieCenter/EitSupport.py:280 __readEitFile DE
14:37:30.021 {   } Plugins/Extensions/EnhancedMovieCenter/EitSupport.py:281 __readEitFile deu

**Comment by Seth72** [comment]
ok i will wait until i get mail from you when it done

regards seth



2015-11-08 14:40 GMT+01:00 hd75hd <notifications@github.com>:

**Comment by betonme** [comment]
@hd75hd What is You prefered EPG language (from the EMC setup)

**Comment by hd75hd** [comment]
prefered EPG language ( in EMC setup ) = German = Deutsch

**Comment by betonme** [comment]
Thanks, please test 60626ad669cb0647d717bbb3995bf8785734c33f

**Comment by betonme** [comment]
@hd75hd 
GS is fixed with d46ef22ec48b3589239b43462f238c9728589ad1

**Comment by hd75hd** [comment]
Thank you .. Now everything runs

**Comment by hd75hd** [comment]
Hello
i found a text-formating issue on some description 

http://www.opena.tv/plugins/12087-beschleunigen-des-emc-post185013.html#post185013

i tested also the last version of it.
Only the version before this commit have not this issue

Regards hd75hf

**Comment by Seth72** [comment]
hello and no its dont work for me at all , i have Movies from Cmore in
seden and get the epgdata in Swedish finish and norwegian and it show all
that in enhanced and information of the Movie , i only want to read
Swedish. the problem is when you get more than one langquish in epgdata .
an old enhanced movive center 1.1.0 work this issue perfekt

regards Seth

2015-11-27 11:46 GMT+01:00 hd75hd <notifications@github.com>:
