### ISSUE TITLE
hide config.EMC.folder

### ISSUE THREAD

**Issue by koivo** [betonme/e2openplugin-EnhancedMovieCenter#138]
Hi,

please hide the config.EMC.folder from hdd.
I think a simple rename from /media/hdd/EMC to /media/hdd/.EMC is possible.

config.EMC.folder  = ConfigTextWOHelp(default = "/media/hdd/.EMC", fixed_size = False, visible_width= 22)

greetings
koivo

**Comment by dhwz** [comment]
Why should we hide the folder per default, that makes no sense? If someone needs it hidden he can change the path by itself?

**Comment by koivo** [comment]
Yes you are right, but i cannot found any option to change this.
I can only see the last point to activate/deactivate the debug log.
First i must activate debug to change the folder.
Second i must restart enigma to use this settings.
Third i must deactivate the option again.
But default EMC creates a folder called EMC on every HDD. Nobody needs this folder.
We need this folder for debug logging, but not default or on every reboot.
You understand what i mean?

**Comment by dhwz** [comment]
OK yes you are right, I'll check this when I'am back from holidays.

**Comment by koivo** [comment]
Thanks
