### ISSUE TITLE
fix option show correct epgdata

### ISSUE THREAD

**Issue by Seth72** [betonme/e2openplugin-EnhancedMovieCenter#139]
hello and merry christmas.
hope that some one here can fix so the correct lang from epgdata .
in this  other enhanced "Suomipoeka101_OE2.0_E2_bh.tgz" its works only to show Swedish , not every lang 

regards seth

**Comment by Seth72** [comment]
why cant this be fixed

**Comment by Fischreiher** [comment]
Continued at https://github.com/betonme/e2openplugin-EnhancedMovieCenter/issues/136
Closed here.
