### ISSUE TITLE
EMC + subssupport

### ISSUE THREAD

**Issue by tzspiros** [betonme/e2openplugin-EnhancedMovieCenter#140]
Is it possible to incorporate in EMC the subssupport tool (mx3L/subssupport) ?
As far as i understand the newest ipk of EMC that includes subssupport is enigma2-plugin-extensions-enhancedmoviecenter_git+935+8a5713a-r2_mips32el.ipk
This is an old version of EMC. The newer versions of EMC can use the subssupport tool?

**Comment by Swiss-MAD** [comment]
Basically EMC don't support "subssupport"
But there gives a EMC fork with "subssupport"  ---> https://code.google.com/p/mediaplayer2-for-sh4/

**Comment by tzspiros** [comment]
It will be nice if EMC incorporates subssupport as a standard feature, considering that several nationalities use subtitles. This is just a proposal for the future.

**Comment by dhwz** [comment]
I'll check that and merge his changes back to the original EMC GIT soon.
