### ISSUE TITLE
EMC automatically re-installs after removal via OPKG

### ISSUE THREAD

**Issue by p17blo** [betonme/e2openplugin-EnhancedMovieCenter#142]
After removal of this pakage using OPKG, it regularly re-installs itself during software update.  I've tried to ascertain is another package is claiming dependency on this but it is not.  How would I stop this from being installed once it has been uninstalled?

**Comment by dhwz** [comment]
Sorry this is no issue related to EMC. Contact your Feed owner for help with that issue.
