### ISSUE TITLE
0 byte cuts since gstreamer 1.6.4 with HD mkv files and some SD mkv files

### ISSUE THREAD

**Issue by deepblue2000** [betonme/e2openplugin-EnhancedMovieCenter#148]
since gstreamer 1.6.4, there are just 0 bytes cuts files on many mkv files,

**Comment by dhwz** [comment]
fixed with https://github.com/betonme/e2openplugin-EnhancedMovieCenter/commit/55888ed45037c0270688ff08575d4bcd827075c9
