### ISSUE TITLE
show the right epg

### ISSUE THREAD

**Issue by Seth72** [betonme/e2openplugin-EnhancedMovieCenter#157]
hello i have ask Before about epg data in emc . i have some channels in my country sweden that i get epg from 3 to 4 different country , Swedish finnish and so on. my question is still why cant it show only Swedish when i want to read about th Movie from epgdata. the bulit in mediplayer can sort this out its only show swedish

**Comment by Seth72** [comment]
#136

**Comment by Fischreiher** [comment]
Continued at https://github.com/betonme/e2openplugin-EnhancedMovieCenter/issues/136
Closed here.
