### ISSUE TITLE
EMC doe not jump to the first marker

### ISSUE THREAD

**Issue by hvorragend** [betonme/e2openplugin-EnhancedMovieCenter#177]
Ich habe das Plugin so konfiguriert, dass es eigentlich immer ab dem ersten Marker Abspielen sollte. Dies funktioniert leider nicht. Es liegen ca. 5 min Vorlauf bis zum Marker. Manuell kann ich dorthin springen.

**Comment by Swiss-MAD** [comment]
Ich meine ich hab das noch so in Erinnerung das nur auf den ersten Marker gesprungen, wenn sich dieser prozentual zur Filmlänge in einem bestimmten Bereich am Anfang befindet.
Ist ja schon Jahre her seit "betonme" diese Funktion eingebaut hatte.
Bei mir funktioniert das seither auch immer wie gewünscht. (auf OE2.0)

**Comment by Swiss-MAD** [comment]
Das scheint ab OE2.2 leider auch kaputt zu sein.....so wie noch ein paar andere Kleinigkeiten. :-(
