### ISSUE TITLE
fix to work on openvix

### ISSUE THREAD

**Issue by Broby1972** [betonme/e2openplugin-EnhancedMovieCenter#185]
having problem to get it to work on open vix. alots of chrashes .

**Comment by dhwz** [comment]
no detailed description what is wrong

**Comment by Broby1972** [comment]
Im no coder but the plugin crash when using setup. And also the selected
subtitles dont stay selected ,  have to choose all the time.

Den 16 feb. 2017 3:12 em skrev "dhwz" <notifications@github.com>:
