### ISSUE TITLE
Hide OsX dot files

### ISSUE THREAD

**Issue by Alexwilmac** [betonme/e2openplugin-EnhancedMovieCenter#186]
Hello, I hope I'm using the correct way to send a question.
Is there a way to hide dot files (not only .DS_Store ones but also every files beginning with a dot in EMC? I saw a file name .gitignore in this repo and I tried to create it within the EMC plugin folder but it didn't work. 
What's the correct way?

**Comment by Swiss-MAD** [comment]
Hi
Look at the file etc/enigma2/emc-hide.cfg
You can switch on - off this option in EMC setup to hide configured files.
This works here on OE2.0 (with a older version of EMC), but under OE2.5 it seems broken.

**Comment by Roenbaeck** [comment]
Is there a workaround/patch for this problem?

**Comment by Swiss-MAD** [comment]
The emc-hide.cfg working on Dreambox OE2.0 and also on DreamOS (OE2.5) as desired.
I tested it with .xxxx files and folders, and i use it daily with "@eaDir" to hide this directories from my Synology NAS.
It seems that OpenBlackHole make something 	different. You'll need to ask the OpenBlackHole developers.
Or using an Image that based on Dream-Multimedia  sources.

**Comment by dhwz** [comment]
Not an EMC bug.
