### ISSUE TITLE
emc crash in openblackhole

### ISSUE THREAD

**Issue by Broby1972** [betonme/e2openplugin-EnhancedMovieCenter#187]
when  in emc /setup emc crash in openblackhole thats is based on openvix.
[output_emc.txt](https://github.com/betonme/e2openplugin-EnhancedMovieCenter/files/781073/output_emc.txt)

select a Movie and subtitles then i Watch and later stop Movie to resume later and if i resume later i have to select the subtitle again. it dont stay selected , try it your self and you will see

**Comment by dhwz** [comment]
Not an EMC bug.

**Comment by Broby1972** [comment]
Hello the same is for every image same bug then vti blackhole atv and more
so then all image have the same bug . So i still use version 3.74 and that
works best.

Den 23 juli 2017 11:36 fm skrev "dhwz" <notifications@github.com>:
