### ISSUE TITLE
.ipk for installation on enigma2

### ISSUE THREAD

**Issue by E2w4UmWh** [betonme/e2openplugin-EnhancedMovieCenter#188]
I'm quite lost!
Where can I get an .ipk-file for installation of EMC on enigma2, or how can I compile this?
I have no clue, from looking into this repository.
Thanks for any hint.

**Comment by Swiss-MAD** [comment]
Geht your daily .ipkg or .deb file on the Newnigma2 Feed --> http://feed.newnigma2.to/daily/
Choose your OE Version (OE2.0 = *.ipkg | OE2.2 & OE2.5 = *.deb) and "mips32el" for all MIPS CPU's or "arm" for ARM CPU's (DM900).

You don't need do compile it anything, only put the Pyton files to your box at the right place.
But do this only when you now what you do. ;)

The regular way is to take a .ipk or .deb file. :-D
