### ISSUE TITLE
Dutch translation file needs to be updated.

### ISSUE THREAD

**Issue by atom89** [betonme/e2openplugin-EnhancedMovieCenter#193]
here is a list of the missing translations.

[MissingTranslations.txt](https://github.com/betonme/e2openplugin-EnhancedMovieCenter/files/977455/MissingTranslations.txt)

**Comment by neoatomic** [comment]
@atom89 Didn't see your post until know... Just updated the Dutch translation today.
Its completed to 100%, (was +- 70%) but still needs work on the verification and naming of some functions. ;)
