### ISSUE TITLE
Dutch Translation.

### ISSUE THREAD

**Issue by atom89** [betonme/e2openplugin-EnhancedMovieCenter#200]
Thanks for the last update, but i found one error.
The help-info for the option: Hide Mini-TV is wrong.

1258 msgid "HELP_hide_miniTV"
1259 msgstr ""
1260 "Verberg bestanden en mappen die opgenomen zijn in '/etc/enigma2/emc-hide."
1261 "cfg'.\n"
1262 "Het aanpassen van deze instelling vereist een herstart van Enigma2!"

it should be like this:

1258 msgid "HELP_hide_miniTV"
1259 msgstr "Mini-TV verbergen"

**Comment by dhwz** [comment]
No everything correct, msgid is not the text which needs to be translated. Check the .pot file.
