### ISSUE TITLE
0 byte .cuts and no markers

### ISSUE THREAD

**Issue by cris10an** [betonme/e2openplugin-EnhancedMovieCenter#201]
Recent versions (2016 up to git20170817) of Enhanced Movie Center is not able to set markers in .cuts files with anything but .ts files, all other media formats produces a zero byte .cuts file that gets deleted when playback is stopped.
The behavior is identical on every type of storage media, (nfs,cifs,hdd,usb,internal flash), an existing .cuts file from a .ts file renamed to an existing non .ts file works just fine.
My receiver is a VU+ Solo2 and the software with problems was OpenBlackhole 1.0 \ OpenPLI 6.0RC, with BlackHole 3.0.3Q \ VTI 11.0.2 \ openATV 6.1 there are no problems at all.

**Comment by Swiss-MAD** [comment]
Why do you search the problem on EMC and not at affected Images ?
On DreamOS and older Dream Images it works as it should.
The reference system for EMC is always a DMM Image.
