### ISSUE TITLE
Ausblenden leerer Verzeichnisse

### ISSUE THREAD

**Issue by achnee1970** [betonme/e2openplugin-EnhancedMovieCenter#202]
Besteht die Möglichkeit eine Anpassung am EMC vorzunehmen, so dass LEERE Verzeichnisse ausgeblendet werden können?
Am besten über Einstellungen steuerbar.
Das würde mir das Leben erheblich erleichtern.

**Comment by ni-hao-1** [comment]
In dem Fall dann nicht nur leere, sondern bitte alle Verzeichnisse ausblenden wo KEINE "abspielbare" (*.ts. *.vob, *.mkv, *.avi, *.mp4 usw.) Dateien dein sind, dann werden leere auch ausgeblendet.


Besteht die Möglichkeit eine Anpassung am EMC vorzunehmen, so dass LEERE Verzeichnisse ausgeblendet werden können?
Am besten über Einstellungen steuerbar.
Das würde mir das Leben erheblich erleichtern.

**Comment by OswaldKolle1977** [comment]
Gibt es hier schon Fortschritte? Vermisse diese Funktion auch sehr! (Bin vom VDR verwöhnt...)
Natürlich kein Ausblenden, falls Unterordner vorhanden sind.....

**Comment by dhwz** [comment]
Ich glaube nicht dass sich jemand die Mühe macht das einzubauen. Da schon eine manuelle Lösung dafür seit Ewigkeiten vorhanden ist, man muss das Verzeichnis nur in die emc-hide.cfg eintragen.
