### ISSUE TITLE
Leeren des Papierkorbs schlägt fehl

### ISSUE THREAD

**Issue by Dieter59** [betonme/e2openplugin-EnhancedMovieCenter#203]
Ich setze die zur Zeit aktuelle Version hier vom GIT ein (git20170817). Seit einiger Zeit bekomme ich in unregelmäßigen Abständen die Meldung "Leeren des Papierkorbs fehlgeschlagen".
Das löschen des Films aus media/hdd funktioniert. Nur wenn der Papierkorb automatisch gelöscht werden soll oder wenn ich aus dem Menü "Papierkorb löschen" auswähle, wird der Film nicht gelöscht und die Meldung erscheint. Löschen mit dem Dateimanager oder per telnet funktioniert.

**Comment by Swiss-MAD** [comment]
Da musst du mal ein Log machen. E2 oder EMC eigenes.
Das Problem hatte ich noch nie.

**Comment by Dieter59** [comment]
Muss ich dazu irgendwelche Debug Optionen zusätzlich einschalten? 
Ich nutze EMC schon seit Jahren und das Problem ist erst vor einigen Wochen aufgetreten und tritt auch nur sporadisch auf. Sowie es nochmal passiert, stelle ich ein Log ein.

**Comment by Swiss-MAD** [comment]
Ein E2 Log müsstest du starten bevor das Problem auftritt.
Im EMC Setup am Ende gibt es die Möglichkeit immer ein Debug Log zu schreiben.

Ein wiederholter Versuch dem Papierkorb zu leeren bringt dann wieder den selben Fehler, oder kann es sein das es dann funktioniert ?
Haben die Dateien vielleicht sehr spezielle Zeichen im Dateinamen, oder sind das Aufnahmen von der Box selbst.

**Comment by Dieter59** [comment]
OK, ich schalte mal den Debug Log des EMC ein.
Es sind sowohl Aufnahmen der Box als auch welche, die mit dem MediaInfo Plugin aufgenommen wurden. Es sind auch Aufnahmen dabei die ein Apostroph und Punkte enthalten (Marvel's Agents of S.H.I.E.L.D.)
Ich habe schon diverse Kombinationen ausprobiert, auch die Marvel's, aber ich konnte das Verhalten nicht provozieren.

**Comment by Swiss-MAD** [comment]
Dann wir es nicht an den Dateinamen liegen. Weil (Marvel's Agents of S.H.I.E.L.D.) zeichne ich jeweils auch auf, hatte noch nie Probleme.
Wobei ich aber in keiner Dreambox Platten mehr verbaut habe, das geht alles nur noch auf's NAS.

**Comment by Dieter59** [comment]
Jetzt habe ich seit 8 Tagen den Log an und natürlich werrden alle 3 Tage alten Dateien aus dem Papierkorb gelöscht, aber ich bleibe dran ... ;-)

**Comment by Dieter59** [comment]
Seit nunmehr 20 Tagen kein Problem mehr, Ich schließe nun den Issue und hoffe, dass er nicht mehr austritt

**Comment by Dieter59** [comment]
s.o.
