### ISSUE TITLE
Crash beim Wechseln in ein spezielles Verzeichnis der Festplatte

### ISSUE THREAD

**Issue by finprog** [betonme/e2openplugin-EnhancedMovieCenter#205]
Wenn ich in eines meiner movie Unterverzeichnisse wechsele stürzt die Box immer ab. Dreambox 520 openatv 6.1

Hier die Log-Ausgaben.
[...]
{   } Plugins/Extensions/EnhancedMovieCenter/EMCFileCache.py:87 addPathToCache EMC addPathToCache /media/hdd/movie/verz1
{   } Plugins/Extensions/EnhancedMovieCenter/MovieCenter.py:265 getPlayerService [EMC] service valid= 1
{ D } Traceback (most recent call last):
{ D }   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 48, in action
{ D }   File "/usr/lib/enigma2/python/Plugins/Extensions/EnhancedMovieCenter/MovieSelection.py", line 2006, in entrySelected
{ D }   File "/usr/lib/enigma2/python/Plugins/Extensions/EnhancedMovieCenter/MovieSelection.py", line 1013, in setNextPath
{ D }   File "/usr/lib/enigma2/python/Plugins/Extensions/EnhancedMovieCenter/MovieSelection.py", line 957, in changeDir
{ D }   File "/usr/lib/enigma2/python/Plugins/Extensions/EnhancedMovieCenter/MovieSelection.py", line 1913, in reloadList
{ D }   File "/usr/lib/enigma2/python/Plugins/Extensions/EnhancedMovieCenter/MovieSelection.py", line 1929, in __reloadList
{ D }   File "/usr/lib/enigma2/python/Plugins/Extensions/EnhancedMovieCenter/MovieCenter.py", line 2731, in reload
{ D }   File "/usr/lib/enigma2/python/Plugins/Extensions/EnhancedMovieCenter/MovieCenter.py", line 1303, in reloadInternal
{ D }   File "/usr/lib/enigma2/python/Plugins/Extensions/EnhancedMovieCenter/MetaSupport.py", line 131, in getMetaDate
{ D }   File "/usr/lib/enigma2/python/Plugins/Extensions/EnhancedMovieCenter/MetaSupport.py", line 116, in getMetaRecordingTime
{ D }   File "/usr/lib/enigma2/python/Plugins/Extensions/EnhancedMovieCenter/MetaSupport.py", line 84, in __mk_int
{ D } ValueError: null byte in argument for int()
[ E ] python/python.cpp:209 call [ePyObject] (PyObject_CallObject(<bound method HelpableActionMap.action of <Components.ActionMap.HelpableActionMap instance at 0x6fc61440>>,('PluginMovieSelectionActions', 'EMCOK')) failed)

**Comment by Swiss-MAD** [comment]
Es kommt vor, das EMC sich an einer .eit oder .meta verschluckt und crasht. Meistens sind es manuell mit einem .eit Editor geänderte .eit.
Das passiert aber eigentlich wenn man mit dem cursor über diese Aufnahme fährt.
Wie ich sehe hast du in EMC den Verzeichnis Cache eingeschaltet. Kann sein das es dann schon beim cachen crasht.

**Comment by finprog** [comment]
Danke! Das wird es wohl gewesen sein. Eine Aufnahme hatte eine sehr kleine .eit Datei (12 Bytes). Von dieser Aufnahme habe ich jetzt alle Dateien in ein anderes Verzeichnis geschoben und jetzt funktioniert es mit dem ursprünglichen Verzeichnis.
Wie / wo kann ich denn beim EMC den Verzeichnis Cache ausschalten, bzw. noch besser den Cache löschen?

**Comment by Swiss-MAD** [comment]
Ja, das .eit Problem ist leider noch ein Bug in EMC.
Den Verzeichnis Cache kannst du in den EMC Einstellungen ausschalten.
Das ist aber schon länger als default Einstellung ausgeschaltet.
Ich meine der Verzeichnis Cache ist auch noch nicht komplett fehlerfrei.
Der Cache wird nur im RAM gehalten, da musst du nichts löschen.

**Comment by dhwz** [comment]
Hoffe das Problem ist hiermit erledigt:
https://github.com/betonme/e2openplugin-EnhancedMovieCenter/commit/941970fd2a9f94872890d70782218b79b1c16ad7
