### ISSUE TITLE
Absturz nach Beendigung des Abspielens einer DVD ISO

### ISSUE THREAD

**Issue by Dieter59** [betonme/e2openplugin-EnhancedMovieCenter#210]
Image VTi 13.0.1 EMC Version git20170817

[dvbapp2_crash_2017-12-17_21-03-48_1513541028.txt](https://github.com/betonme/e2openplugin-EnhancedMovieCenter/files/1566010/dvbapp2_crash_2017-12-17_21-03-48_1513541028.txt)

**Comment by atvcaptain** [comment]
ask vti team, to fix his close source e2
