### ISSUE TITLE
EitSupport - Sonderzeichen

### ISSUE THREAD

**Issue by brkulin** [betonme/e2openplugin-EnhancedMovieCenter#211]
Der neueste EitSupport.py patch führt dazu, dass enigma2 für spezielle CZE, SLO, SLK und HR Zeichen fällt.

**Comment by dhwz** [comment]
then provide a WORKING patch, else this will stay as it is right now

**Comment by brkulin** [comment]
[EitSupport.txt](https://github.com/betonme/e2openplugin-EnhancedMovieCenter/files/1595035/EitSupport.txt)
The test is not OK.
It only works with this file:

**Comment by dhwz** [comment]
Sadly that breaks real Unicode data again, we need some way to detect if we need your decoding and then apply it only if necessary.

**Comment by brkulin** [comment]
I attach 2 files. Arrow.eit is a year old and Mummy is from this year (recorded with a newer version of VTi image).
[eit.zip](https://github.com/betonme/e2openplugin-EnhancedMovieCenter/files/1595150/eit.zip)

**Comment by dhwz** [comment]
Ok you have the same issue as we have in Germany, Python doesn't know the xc2 Unicodebyte thats why we land in the Exception. Please try the new code below (just a test, it's looking good for me with your DVB .eit files, but this may break support for user created .eit with other codepages).

https://pastebin.com/tqPayx0X

**Comment by dhwz** [comment]
try this one: https://pastebin.com/raw/8x534FU7

**Comment by brkulin** [comment]
This fix does not cause a fall, but the Czech (eg, č,ž,ř,ě,á....) characters are not displayed.

**Comment by dhwz** [comment]
With one of the examples you gave me? Check the logfile if you get an exception message.

**Comment by brkulin** [comment]
Yes. This is true for both examples. I've also tried a new recording and the characters are also missing. The exception report is not displayed.

**Comment by dhwz** [comment]
Hm ok strange as your data seems to be UTF-8, ok give this a try https://pastebin.com/raw/kgZ8rjMA

**Comment by brkulin** [comment]
So this looks very good! Only the characters á, í, é, ý, ú are displayed as a, i, e, y, u.

**Comment by brkulin** [comment]
Does not matter. I will use the older file for now.
I wish you many successes and a Happy New Year.

**Comment by dhwz** [comment]
Ok, I've committed a new file which should fix most of our problems, your workaround for CZ/SK is still needed, but it's only executed if the right codepage is detected.

**Comment by brkulin** [comment]
Good job! Everything is OK!
You are the best!
Thanks.

**Comment by dhwz** [comment]
Happy New Year!
Can you tell me some examples which services you did record with VTi, just wanna try if this is really a EMC issue or just a bug in VTi.

**Comment by brkulin** [comment]
I tried to record different programs Skylink 23.5E Astra (Nova Cinema HD, CT1 HD, Prima Cool HD ...). Right now I'm recording Johnny English (Prima HD).

**Comment by dhwz** [comment]
See: http://fs1.directupload.net/images/180101/mskjxtdu.jpg
With this code: https://pastebin.com/raw/J4SxV1Ha

Then let me say that this all just a huge VTi bug, so we really shouldn't use this whole CZ/SK patch and instead VTi should fix their code properly.
