### ISSUE TITLE
menü ist teilweise in englich

### ISSUE THREAD

**Issue by dazlak69** [betonme/e2openplugin-EnhancedMovieCenter#212]
das Menü ist hier noch teilweise in englisch und auch teilweise großgeschrieben.

<DUMMY CONFECTION>
display Settings
DVD/Blue-ray Folders

**Comment by dhwz** [comment]
No issue

**Comment by dazlak69** [comment]
sieht bei mir so aus.
ich habe alle dateien aus dem ordner /src überschrieben.

![1_0_19_2eaf_411_1_c00000_0_0_0](https://user-images.githubusercontent.com/22277299/34469372-c8305a3e-ef1d-11e7-891b-f1317ca7e866.jpg)

**Comment by dhwz** [comment]
Wie ich schon sagte kein Fehler, das ist ein Enwicklungs-GIT keines für Endanwender...

**Comment by dazlak69** [comment]
das ist das Aktuelle VTI 13.0.2 mit iFlatFHD skin

**Comment by dhwz** [comment]
Hm komisch weil da sollten nach jeder Sektionsüberschrift Trennstriche sichtbar sein.
