### ISSUE TITLE
Einstellungen/ALLGRMEIN teilweise ohne Funktion

### ISSUE THREAD

**Issue by dazlak69** [betonme/e2openplugin-EnhancedMovieCenter#213]
Einstellungen/ALLGEMEIN
starte EMC mit: hat bei allen Einstellmöglichkeiten außer mit "Video Taste" keine funktion.

auch wird nur das EMC setup Menü im Erweiterungsmenü angezeigt.
EMC selbst lässt sich nicht aufrufen.

**Comment by dhwz** [comment]
No issue
