### ISSUE TITLE
VTI Jugendschutz greift nicht im EMC

### ISSUE THREAD

**Issue by dazlak69** [betonme/e2openplugin-EnhancedMovieCenter#214]
der VTI Jugendschutz greift nicht im EMC
zb.
- lassen sich Filme  ohne lösch PIN löschen
- Film verzeichnisse lassen sich auch noch nicht schützen...
könnte man man das evtl. noch mit einbauen?

**Comment by dhwz** [comment]
EMC ist kein VTi Plugin, es werden keine propietären Imagefunktionen unterstützt.

**Comment by Swiss-MAD** [comment]
Verzeichnisse lassen sich schon lange vor versehentlichem löschen schützen.
Einfach IM Verzeichnis über MENU die entsprechende Funktion wählen.
Der Rest wie dhwz schrieb.
