### ISSUE TITLE
Jump to next marker works just once (no second jump possible)

### ISSUE THREAD

**Issue by starbrights** [betonme/e2openplugin-EnhancedMovieCenter#215]
Jumping from one marker to next is not working - only once.
After that I have to move forward or backward until I can do next jump.

Other way: I can't do more than once jump  (|<<  or  >>| ).

---

Das Springen zum nächsten Marker funktioniert, aber nur einmal. Beim zweiten Drücken der Jump-Taste passiert nichts mehr. Man muss erst ein wenig weiter "spulen" ehe man den nächsten Sprung machen kann.

**Comment by dhwz** [comment]
Kein Fehler feststellbar, funktioniert problemlos.

**Comment by starbrights** [comment]
Du hast recht, das passiert auch im Image-eigenen Abspieler. Sorry!
