### ISSUE TITLE
Farbe in der File-Liste

### ISSUE THREAD

**Issue by starbrights** [betonme/e2openplugin-EnhancedMovieCenter#216]
Der aktuelle Skin bringt es mit sich, das die noch nicht abgespielten Files (default unter 5%) praktisch nicht mehr lesbar sind (dunkelgraue Schrift auf Schwarz). 
Da ich keinen eigenen Skin verwende ist das problematisch. Derzeitiger Workaround für mich: die angepielten Files statt auf 5% auf  0% stellen - sie werden dann alle gelb - das ist lesbar.
Allerdings wird es wieder schlecht lesbar, wenn das File ausgewählt wird, dann gibt es mit gelb auf weißem Hintergrund wenig Kontrast.

PS: Wie kann ich hier den Issue-Namen (Überschrift) ändern?!?

**Comment by dhwz** [comment]
Das liegt aber hauptsächlich an den Farben die dein E2-Skin definiert, denn EMC übernimmt die in dem Skin nur. Daher lässt sich das auch nicht wirklich ändern.

**Comment by starbrights** [comment]
Ich hatte damit vorher nie Probleme. Das war erst nach einem kürzlichen Update da.
Verwende das HDF Image - benutze keinen Skin, nur den Backup/default. Der beinhaltet laut HDF keine Formatierung zu EMC.
Schätze das liegt an der Änderung vom 26.12. mit der auch die Git-Nummer oben eingeblendet wird. Sicher praktisch, aber da geht Platz verloren und der WAF (Womans Acceptance Factor) ist auch ziemlich Null.
Das soll eure tolle Arbeit aber nicht abwerten - bitte nicht falsch verstehen. :)

**Comment by dhwz** [comment]
Ja daher sagte ich ja die Farben werden von deinem HDF Skin übernommen, in dem Default Skin sind sogut wie keine eigenen Farben definiert, sondern verweisen auf fixe Namen, so dass das Skin sich automatisch an das verwendete Hauptskin anpasst.
Das alte Defaultskin war ja statisch das war nicht auf das Hauptskin abgestimmt.

**Comment by starbrights** [comment]
Mag sein, aber der funktionierte wenigstens ;)
Ich kenn mich da jetzt wirklich wenig aus, aber ich denke das EMC entweder 
a) die Farben vom Image-Skin übernimmt oder
b) eigene Default-Farben verwendet.

Sonst macht doch die Einstellungen (Skin verwenden oder nicht) keinen Sinn.
Und b) - was in Verantwortung von EMC liegt, sollte lesbar sein, auch wenn es sich nicht harmisch in das Image einbringt (was man mit a) verhindern könnte).

Jetzt scheint es eine Mischung zu geben. Vielleicht ist die Farbe von euch, der Background vom "Skin"? Ich weiß es nicht.

Naja, letztlich kann ich nur bitten, aber ich meine mein Anliegen hätte eine Berechtigung.  Klar steh ich jetzt zwischen Baum und Borke, zwischen Plugin und Image.

Aber ein paar Sachen stehen auch statisch im Code, zumindest sehe ich das in der Änderung vom 26. (gelb ... backround transparent .... ohne das wirklich zu verstehen)

commit 2dc75465c88b16aa27f7c51153415dc36c389dbd

**Comment by dhwz** [comment]
Das kann nicht für jeden Skin passend gemacht werden, wenn es nicht gut ausschaut muss es eben in dem entsprechenden Skin angepasst werden.
