### ISSUE TITLE
After pause: subtitle gone for 30 sec

### ISSUE THREAD

**Issue by AndKe** [betonme/e2openplugin-EnhancedMovieCenter#218]
Observed on DM900
Reproduce:
During video playback with subtitles
press pause, press play/unpause
observe that there are no subtitles for 30seconds.
at 30sec, the video is corrupted for a short time, and subtitles are back.

This is fully reproducible every time.

**Comment by dhwz** [comment]
Thats no an EMC issue.

**Comment by AndKe** [comment]
Just to clarify, I did not know it, but now assume EMC is an frontend, and does not do the actual video/subtitle decoding/playing. - sorry.
