### ISSUE TITLE
Please add subtitle preferance "any"

### ISSUE THREAD

**Issue by AndKe** [betonme/e2openplugin-EnhancedMovieCenter#219]
Some subtitles are not detected as an particular language. so they are not displayed with the auto-show-subtitles setting).
Please add "any" to language preferences, so that if first language is not found, nor second , then third can match "any" or "unknown" 

Thank you.

**Comment by dhwz** [comment]
See https://github.com/betonme/e2openplugin-EnhancedMovieCenter/commit/ca3cab1624eb7100697736dbf474d06bcedf8bfe

You should use Undefinied (und) or Multiple Languages (mul) or Miscellaneous languages (mis).
