### ISSUE TITLE
Crash with Version 1.0git20180105-r1

### ISSUE THREAD

**Issue by yottabyte1972** [betonme/e2openplugin-EnhancedMovieCenter#220]
Please Help.

EMC crashes when started.... (dm7020hd) since last update.

logs attached.

Thx Yottabyte1972

[enigma2_crash_1515396060.log](https://github.com/betonme/e2openplugin-EnhancedMovieCenter/files/1610834/enigma2_crash_1515396060.log)

**Comment by dhwz** [comment]
If you doing an update from the GIT then you are responsible to fullfill all requirements which you didn't to.

python-requests is missing

**Comment by yottabyte1972** [comment]
I did nothing manual, this was triggered by a reboot of the dreambox.
What can i do?
Do you prefer German? Wäre einfacher :-)

Danke für die schnelle Antwort....

**Comment by dhwz** [comment]
Mir egal von mir aus auch auf Deutsch ;)
Wenn du nicht manuell aktualisiert hast, dann ist dein Imagebetreiber schuld der das EMC vom GIT aktualisiert aber die Depends nicht entsprechend ergänzt hat.

Wie gesagt beheben kann man es indem man python-requests nachinstalliert.

**Comment by yottabyte1972** [comment]
i installed "python-requests", now it works again.

Thx for "Super Fast Help"

Yottabyte
