### ISSUE TITLE
Feature Request: Handling von wiederholenden Timern beim Löschen von laufenden Timer-Aufnahmen

### ISSUE THREAD

**Issue by dream-alpha** [betonme/e2openplugin-EnhancedMovieCenter#221]
Beim Löschen von laufenden Timeraufnahmen werden momentan reguläre Timer mitgelöscht.
Es wäre toll, wenn beim Löschen von wiederholenden Timer-Aufnahmen der dazugehörige Timer deaktiviert und wieder aktiviert würde. Momentan muss man das manuell machen, was die Sache umständlich macht.
Bitte um wohlwollende Behandlung ;-) Danke.

**Comment by Swiss-MAD** [comment]
Noch besser wäre es aus meiner Sicht wenn die reguläre E2 abfrage kommt, was mit zukünftigen Ereignissen geschehen soll.

**Comment by dream-alpha** [comment]
oder so ;-)

**Comment by dhwz** [comment]
Muss erstmal den Code verstehn, kommt da überhaupt noch die Meldung "Not stopping any repeating timers. Modify them with the timer editor."?

**Comment by Swiss-MAD** [comment]
Früher kam die Meldung sicher.
Aber schon lange nicht mehr probiert, weil ich gleich ins Timer menu ging. ;)

**Comment by dhwz** [comment]
Hm ok muss mir mal anschauen was der Timereditor da genau macht und ob man das so einfach übernehmen kann.

**Comment by dhwz** [comment]
@Swiss-MAD 
Das ist die Abfrage die du dann immer siehst oder? "Repeating event currently recording... What do you want to do?"

**Comment by Swiss-MAD** [comment]
Ja genau. Der Wunsch wäre also wenn man in EMC einen noch laufenden wiederholenden Timer löschen will, erst diese Abfrage vom E2 Timer Editor erscheint. Danach kann man dann die Aufnahme bei Bedarf löschen.

**Comment by dream-alpha** [comment]
eigentlich waere der wunsch so: wenn man in der movielist mit der roten taste den film loeschen will, kommt diese abfrage und nach beantwortung wird die timeraktion durchgefuehrt und der film geloescht. 
alles in einem rutsch.

**Comment by Swiss-MAD** [comment]
Nein bitte nicht in einem Rutsch!
Genau so wie bei einem einzelnem Timer, einfach mit der Abfrage dazwischen.
Weil sonst wird einem die Möglichkeit genommen, einen laufenden Timer in EMC einfach zu beenden, und nach Wunsch erst danach zu löschen.
Das Nutze ich noch ab und zu bei einzel Timern, wenn ich sehe das die Nachlaufzeit nicht nötig ist.
Das ist je nach dem ob man die Löschabfrage drin hat oder nicht einen oder 2 Tasten mehr. Das müsste drin liegen. ;)
Notfalls im Setup einstellbar, ob danach sofort auch gelöscht wird, oder nicht.
Sollte dann für einzel und wiederholenden Timern gleichzeitig gelten.

**Comment by svenh0** [comment]
Und wenn beim Löschen im EMC anstatt der bisherigen Frage 
"Laufende Aufnahme beenden? ....ja/nein"
eine ChoiceBox kommt?
Es handelt sich um eine laufende Aufnahme. 
Was wollen sie machen ?
- nur den Timer beenden
- den Timer beenden und Aufnahme löschen
- Abbrechen

Wenn es ein wiederkehrender Timer ist, könnte danach ja dann die Frage von E2 kommen:
Wiederholender Timer ist zur Zeit aktiv... Was wollen Sie machen?
- laufendes Ereignis abbrechen, aber kommende ausführen
- laufendes Ereignis abbrechen und kommende ignorieren
- Aktuelle Aufnahme nicht beenden aber künftige ignorieren

Oder es wird nach der 1. Frage code-intern automatisch die Variante 1 für den wiederkehrenden Timer gesetzt (laufendes Ereignis abbrechen, aber kommende ausführen), also ganz ohne 2. Frage. 
Das wäre meiner Meinung nach dann ja die sinnvollste Variante aus dem EMC heraus.

**Comment by dream-alpha** [comment]
ja, genau so wie svenh0 es beschreibt, meine ich es auch.

**Comment by svenh0** [comment]
das dürfte der passende Code-Teil vom TimerEditor sein.
Variante 1 = stoponlycurrent bei "if t.repeated:"
https://github.com/libo/Enigma2/blob/master/lib/python/Screens/TimerEdit.py#L91

Nur eben den Code aus dem CallBack direkt anstelle der ChoiceBox für den wiederkehrenden Timer verwenden.

Das müsste dann hier rein - anstelle von "return False"
https://github.com/betonme/e2openplugin-EnhancedMovieCenter/blob/master/src/RecordingsControl.py#L189

**Comment by svenh0** [comment]
die geänderte Funktion "stopRecording" in der RecordingsControl.py funktioniert bei mir schon mal auch für das Beenden von wiederkehrenden Timern.
Fehlt nur noch vorneweg die ChoiceBox, ob man nur den Timer beenden möchte oder auch gleich die Aufnahme löschen möchte ;) 

```
	def stopRecording(self, filename):
		try:
			if filename[0] == "/":			filename = os.path.basename(filename)
			if not isDreamOS:
				if filename.lower().endswith(".ts"):	filename = filename[:-3]
			if filename in self.recDict:
				for timer in NavigationInstance.instance.RecordTimer.timer_list:
					if timer.isRunning() and not timer.justplay and timer.Filename.find(filename)>=0:
						if timer.repeated:
							#return False
							timer.enable()
							timer_afterEvent = timer.afterEvent
							timer.afterEvent = AFTEREVENT.NONE
							timer.processRepeated(findRunningEvent = False)
							NavigationInstance.instance.RecordTimer.doActivate(timer)
							timer.afterEvent = timer_afterEvent
							NavigationInstance.instance.RecordTimer.timeChanged(timer)
						else:
							timer.afterEvent = AFTEREVENT.NONE
							NavigationInstance.instance.RecordTimer.removeEntry(timer)
						emcDebugOut("[emcRC] REC STOP for: " + filename)
						return True
			else:
				emcDebugOut("[emcRC] OOPS stop REC for nonexistent: " + filename)
		except Exception, e:
			emcDebugOut("[emcRC] stopRecording exception:\n" + str(e))
		return False
```

**Comment by dream-alpha** [comment]
das sieht doch schon mal nicht schlecht aus.... und wuerde meinen usecase bereits abdecken, weil in 90% der cases will man ja den wiederholenden timer nicht loeschen sondern nur das aktuelle event  beenden aber den timer fuer zukuenftige events weiterlaufen lassen.

**Comment by dhwz** [comment]
Sorry aber das macht für mich keinen Sinn, der Button heißt löschen also sollte er auch löschen und nicht nur den Timer stoppen,

**Comment by svenh0** [comment]
Da muss ich aber widersprechen. 
Die Frage im EMC lautet: „soll die laufende Aufnahme beendet werden?“

Da steht nichts von Timer.

**Comment by dream-alpha** [comment]
@dhwz: ja genau... das war vielleicht nicht klar... wenn man auf die rote taste "loeschen" drueckt, dann wird der film auf jeden fall geloescht. das timer-handling ist zusaetzlich.

**Comment by dhwz** [comment]
@svenh0 
Ich sprech nicht vom Timer, sondern von der Aufnahme.

**Comment by dream-alpha** [comment]
genau, das file soll auf jeden fall geloescht werden.

**Comment by svenh0** [comment]
Wir haben hier ja 2 Baustellen. 
1. Timerhandling
Mit dem obigen Code können jetzt auch wiederkehrende Timer berücksichtigt werden. 

2. Löschen von Aufnahmen (auch wenn die Aufnahme gerade läuft)
Genau das geht im Moment nicht. Es wird nur die Aufnahme beendet. 
Löschen muss ich die Aufnahme dann mit nochmaliger roter Taste. 
Deshalb war ja der Kompromiss mit der Choicebox als Multilösung.

**Comment by Swiss-MAD** [comment]
Dennoch macht es Sinn zuerst zu fragen ob der noch laufenden Timer wirklich beendet werden soll.
Ob dann gleich auch die Aufnahme dazu gelöscht werden soll sollte danach aber nochmal angefragt werden.

**Comment by dhwz** [comment]
Also ich würde bevorzugen den Timer gar nicht anzupacken, dass der Timer geöscht wird macht ja bei Single-Events auch Sinn. Bei wiederholenden Timer, will man ja die laufende Aufnahme dann löschen, folglich sollte der Timer selbst auch nicht verändert/gelöscht werden. EMC ist kein Timer-Editor!

**Comment by dhwz** [comment]
@Swiss-MAD 
Das passiert doch jetzt auch nicht bei einem Single-Event?

**Comment by svenh0** [comment]
Ich finde die jetzige Lösung inkonsequent. 
Warum sollte man nicht auch wiederkehrende Timer beenden können. 

Es kommt ja vorher auch die Frage, ob man die Aufnahme beenden will. 

Da finde ich den Hinweis auf den TimerEditor eher primitiv, zumahl es EMC mit obigen Code selber machen könnte. 

Ich merke aber, dass das offensichtlich trotz Wunsch in #221 nicht gewollt ist.

**Comment by dhwz** [comment]
Also es sollte IMHO identisch behandelt werden nur dass der Timer eben nicht gelöscht sondern nur gestoppt wird.

**Comment by Swiss-MAD** [comment]
Doch jetzt wird erst gefragt ob der Timer beendet werden soll, (weil sonst die Aufnahme nach dem löschen wieder fortgesetzt wird....war zumindest früher im OE2.0 so. Auf OE2.5 habe ich das nicht ausprobiert) danach konnte man erst löschen.

EMC soll auch kein Timer Editor werden, aber die Möglichkeit den noch laufenden Timer in EMC schnell zu stoppen ohne auch gleich die Aufnahme zu löschen finde ich schon sehr praktisch.

**Comment by dhwz** [comment]
@Swiss-MAD 
Du missverstehst mich, exakt das macht doch die Änderung von Sven. Es ging um die Timer!

**Comment by Swiss-MAD** [comment]
Ja die Lösung von Sven gefällt mir.
Danach noch die Frage ob der Film auch gleich gelöscht werden soll, und dann finde ich das eine Runde Sache. ;)

Ja wiederholende Timer sollen nicht einfach so gelöscht werden. Entweder stoppen, oder choice box vom Timer Editor.
Oder meinst du noch was anderes? ....muss mal Kaffee machen. ;)

**Comment by Swiss-MAD** [comment]
Ja wenn der Timer nicht mehr läuft, muss natürlich auch nichts am Timer gedreht werden.

**Comment by svenh0** [comment]
Ja, genauso behandeln wie jetzt nur den wiederkehrenden eben nur stoppen. 
Es geht ja eigentlich um das Löschen der Aufnahme. 
Dazwischen kommt ja nur das Timerhandling. 

Er möchte ja das Beenden eines Timers und Löschen der Aufnahme in einem Rutsch mit einer ChoiceBox. 
Weil jetzt muss man mit rot erst die Aufnahme beenden und dann, wenn man möchte, nochmal mit rot die Aufnahme löschen. 
Mit der ChoiceBox bei der Timer-Beenden-Frage könnte man das Löschen direkt ausführen sofern gewünscht. 
Die Option nur den Timer zu beenden würde ich dabei lassen, weil das jetzt bestimmt auch einige in EMC so nutzen.

**Comment by Swiss-MAD** [comment]
Ja, ungefähr so hätte ich mir das vorgestellt. :D

**Comment by dhwz** [comment]
Okay, naja das mit der Abfrage ist ja auch kein Problem, allerdings brauchen wir da keine ChoiceBox sondenr einen normale MessageBox mit Ja/Nein reicht da dann völlig und bei Ja rufen wir einfach noch das self.deleteMovieQ auf nachdem self.stopRecordQ aufgerufen wurde, dann gilt das nämlich auch für alles Single-Events und Multi-Events.

**Comment by Swiss-MAD** [comment]
Ja, das tönt gut. ;)

**Comment by svenh0** [comment]
Also nur bei einer laufenden Aufnahme folgende ChoiceBox:
Es handelt sich um eine laufende Aufnahme.
Was wollen sie machen ?

- nur den Timer beenden
- den Timer beenden und Aufnahme löschen
- Abbrechen

Punkt 1 funktioniert ja schon - bisherige Variante in EMC (mit obigen Code jetzt auch für wiederkehrende Timer)
Punkt 2 müsste irgendwie noch integriert werden. Also nach Löscheb/Beenden der Timer auch das File löschen, sofern eben Punkt 2 gewählt wurde.

**Comment by dhwz** [comment]
Ok, dann mach ich das später so oder Sven wenn er lustig ist, aber da muss auch bissl aufgeräumt werden dann ;)

**Comment by svenh0** [comment]
Ok, 2 nacheinanderfolgende Fragen ja/nein ginge auch. 
Die ChoiceBox wäre dann luxus ;)

**Comment by dream-alpha** [comment]
in der zweiten checkbox bitte den default sinngemaess auf "der wiederholende timer soll nicht komplett geloescht werden, sondern nur angehalten werden" setzen, weil das imho der hauptanwendungsfall ist.

**Comment by dhwz** [comment]
Wie gesagt am Timer wird ja nichts gemacht die Abfrage sollte sich auf die AUFNAHME beziehen. Die Abfrage heißt ja auch jetzt schon ob man die laufenden Aufnahme stoppen möchte, von Timer löschen steht da ja nirgendwo etwas.

**Comment by svenh0** [comment]
Wie gesagt, mit den 2 Fragen könnte ich auch leben. 
Auf jeden Fall ein Fortschritt zum jetzigen Stand ;)

Die #221 könnte man ja mit obigen Code schon erledigen. 
Zum direkten Löschen der Aufnahme nach Beenden des Timers könnte man ja einen neuen Punkt aufnachen. 

Oder soll das hier alles komplett fertig gemacht werden?

**Comment by dhwz** [comment]
Ich würd das hier fertig machen, ist ja nicht mehr viel.

**Comment by svenh0** [comment]
Ok ;)

Ich glaube mit dem Aufruf von self.deleteMovieQ direkt nach dem  self.stopRecordQ würde dann auch eine Mischauswahl (laufende und fertige Aufnahmen) bei Mehrfachauswahl berücksichtigen. 
Jetzt werden glaub ich nur die Timer beendet. 
Die mitgewählten fertigen Aufnahmen werden bisher ignoriert, wenn man auch laufende Aunahmen ausgewählt hat. 

Also gleich mehrere Fliegen mit einer Klappe ;)

Ich teste das Nachmittag mal. Ist ja nur eine zusätzliche Codezeile ;)
Die Variante mit der ChoiceBox wäre da nicht so einfach.

**Comment by Swiss-MAD** [comment]
2 Abfragen hintereinander passt doch. Da würde ich keine Zeit in eine ChoiceBox investieren.
Und wie dhwz schrieb macht man damit bei der Übersetzung auch nichts kaputt.

**Comment by dream-alpha** [comment]
@svenh: wenn du magst, kannst du mir das auch zum testen geben.

**Comment by dream-alpha** [comment]
ja, hier anhaengen waere das einfachste... denke ich.

**Comment by svenh0** [comment]
Ich hab das mit der zusätzlichen Zeile zum Löschen gerade mal probiert:
https://github.com/betonme/e2openplugin-EnhancedMovieCenter/blob/master/src/MovieSelection.py#L2356

			if len(self.recsToStop)>0:
				self.stopRecordQ()
				self.deleteMovieQ(selectedlist, self.remRecsToStop)
			else:
				self.deleteMovieQ(selectedlist, self.remRecsToStop)

@dhwz 
Leider klappt das nicht, da E2 die Funktionen direkt nacheinander feuert und somit die Löschfrage schon zu sehen ist, obwohl man die Timer-Beenden-Frage noch gar nicht beantwortet hat.
Gibt es ein einfaches CallBack für normale Funktionen, so dass self.deleteMovieQ erst nach return von self.stopRecordQ ausgeführt wird ??

Die funktionierende RecordingsControl.py zum Beenden von wiederkehrenden Timern hänge ich hier schon mal an.

[RecordingsControl.zip](https://github.com/betonme/e2openplugin-EnhancedMovieCenter/files/1623250/RecordingsControl.zip)

**Comment by svenh0** [comment]
Hab es hinbekommen ;) 
Hier nun noch die geänderte MovieSelection.py:
[MovieSelection.zip](https://github.com/betonme/e2openplugin-EnhancedMovieCenter/files/1623339/MovieSelection.zip)

**Comment by dhwz** [comment]
Hm, ich hatte mir das anders gedacht ich muss mal mal hier ausprobieren.

**Comment by svenh0** [comment]
Die Funktionsweise ist jetzt aber genauso wie zuvor ausgemacht ;)

**Comment by dhwz** [comment]
Nein, ich wollte dass die Abfrage für JEDEN einzelnen Timer kommt. ;)
Wie gesagt lass mich mal machen.

**Comment by svenh0** [comment]
Wenn ich aber mehrere markiere und beenden möchte, ist das doch korrekt. 
Wenn ich nur einen beenden möchte, dann muss ich den einzeln auswählen und rot drücken. 
Versteht das Problem nicht ;)

**Comment by dhwz** [comment]
Hast du doch vorhin selbst schon beantwortet wenn dann einer fehlschlägt gilt das für alle.

**Comment by svenh0** [comment]
ok, das stimmt.
Aber dann für jeden Timer 2 Frage beantworten, wäre ja auch doof ;)
wobei ich zu 99% eh nur einen Timer beende.

**Comment by dhwz** [comment]
Eben, lass es mich mal abändern, dann können wir immer noch drüber reden. :)

**Comment by svenh0** [comment]
Was hältst du von dieser Idee ?

Es wird versucht, alle Timer zu beenden.
Wenn einer fehlschlägt, dann geht der filename in eine Liste zum Anzeigen in der späteren Messagebox.
Zeitgleich wird der fehlgeschlagene Timer aus der self.deleteList entfernt, so dass diese Aufnahme später nicht gelöscht wird.
Zum Schluss kommt die Meldung, dass einige Timer nicht beendet werden konnten, man solle es über den TimerEditor machen (mit Anzeige der filename-Liste).
Danach kommt dann die Frage zum Löschen der übrigen Aufnahmen.

Nur die Zeile "remove filename from self.deleteList" ist noch nicht echt (nur die Idee).

	def stopRecordConfirmation(self, confirmed):
		if not confirmed: return
		# send as a list?
		stoppedAll=True
		filenames = "\n"
		for e in self.recsToStop:
			stoppedResult = self["list"].recControl.stopRecording(e)
			stoppedAll = stoppedAll and stoppedResult
			if stoppedResult = False:
				filenames += "\n" + e.split("/")[-1][:-3]
				remove filename from self.deleteListe # Zeile muss noch realisiert werden
		if not stoppedAll:
			self.checkHideMiniTV_beforeFullscreen()
			self.session.open(MessageBox, _("Not stopping any timers. Modify them with the timer editor.") + filenames, MessageBox.TYPE_INFO, 10)
			self.deleteMovieQ(self.deleteList, self.remRecsToStop)
		else:
			self.deleteMovieQ(self.deleteList, self.remRecsToStop)

**Comment by dhwz** [comment]
Ähm kannst du Gedanken lesen? ;)
Ja ich hab nur noch die Sache mit dem löschen des Filesnames noch nicht gelöst.

**Comment by svenh0** [comment]
evtl. noch etwas umständlich ;)

	def stopRecordConfirmation(self, confirmed):
		if not confirmed: return
		# send as a list?
		stoppedAll=True
		filenames = "\n"
		print "========= self.recsToStop", self.recsToStop
		print "========= self.deleteList", self.deleteList
		for e in self.recsToStop:
			stoppedResult = self["list"].recControl.stopRecording(e)
			stoppedAll = stoppedAll and stoppedResult
			if stoppedResult == False:
				filenames += "\n" + e.split("/")[-1][:-3]
				i=0
				for service in self.deleteList:
					print "===== deleteList.path ", service.getPath(), e
					if service.getPath() == e:
						del self.deleteList[i]
						break
					i += 1
					#		remove filname from self.deleteListe
		if not stoppedAll:
			self.checkHideMiniTV_beforeFullscreen()
			self.session.open(MessageBox, _("Not stopping any timers. Modify them with the timer editor.") + filenames, MessageBox.TYPE_INFO, 10)
			self.deleteMovieQ(self.deleteList, self.remRecsToStop)
		else:
			self.deleteMovieQ(self.deleteList, self.remRecsToStop)

**Comment by dhwz** [comment]
Ja so geht es auch ich hatte mir gedacht wir ergänzen den Index einfach direkt beim hinzufügen, also in self.recsToStop mit angeben, dann musst nicht danach umständlich danach suchen.

**Comment by svenh0** [comment]
ok, da wollte ich nichts ändern, weil ich nicht weiß, ob eine geänderte Struktur von self.recstostop irgendwo Probleme macht.
Hab aber gerade geschaut, das wird nirgendwo anders genutzt.
Also könnte man auch bei Aufbau der Listen (delete/recstostop) einen zähler rein nehmen und dann bei recstostop den index mitgeben.
Dann müsste der Code bei e... auf e[0]... geändert werden.
Und der Index zum del self.deleteListe(e[1])

**Comment by dhwz** [comment]
ja genau

**Comment by svenh0** [comment]
machst du das ?

**Comment by dhwz** [comment]
ja kann ich machen, dann übernehm ich erstmal deinen Code von oben

**Comment by svenh0** [comment]
hab hier doch schon was, allerdings noch ungetestet:

Hab zum anschließenden Löschen noch ne Abfrage reingenommen, falls nach den Timer-Fehlern nichts mehr zum Löschen übrig ist ;) 

	def stopRecordConfirmation(self, confirmed):
		if not confirmed: return
		# send as a list?
		stoppedAll=True
		filenames = "\n"
		for e in self.recsToStop:
			stoppedResult = self["list"].recControl.stopRecording(e[0])
			stoppedAll = stoppedAll and stoppedResult
			if stoppedResult == False:
				filenames += "\n" + e[0].split("/")[-1][:-3]
				del self.deleteList[e[1]]
		if not stoppedAll:
			self.checkHideMiniTV_beforeFullscreen()
			self.session.open(MessageBox, _("Not stopping any timers. Modify them with the timer editor.") + filenames, MessageBox.TYPE_INFO, 10)
			if len(self.recsToStop)>0:
				self.deleteMovieQ(self.deleteList, self.remRecsToStop)
		else:
			self.deleteMovieQ(self.deleteList, self.remRecsToStop)

	def stopRecordQ(self):
		try:
			filenames = ""
			for e in self.recsToStop:
				filenames += "\n" + e[0].split("/")[-1][:-3]
			self.checkHideMiniTV_beforeFullscreen()
			self.session.openWithCallback(self.stopRecordConfirmation, MessageBox, _("Stop ongoing recording?\n") + filenames, MessageBox.TYPE_YESNO)
		except Exception, e:
			emcDebugOut("[EMCMS] stopRecordQ exception:\n" + str(e))

und das hier ab Zeile 2253 oder so:

			else:
				if self["list"].serviceBusy(selectedlist[0]): return
				if selectedlist and len(selectedlist)>0:
					self.recsToStop = []
					self.remRecsToStop = False
					i=0
					for service in selectedlist:
						path = service.getPath()
						movieFileCache.delPathFromCache(os.path.dirname(path))
						if self["list"].recControl.isRecording(path):
							self.recsToStop.append([path,i])
						i += 1
						if config.EMC.remote_recordings.value and self["list"].recControl.isRemoteRecording(path):
							self.remRecsToStop = True
					if len(self.recsToStop)>0:
						self.deleteList = selectedlist
						self.stopRecordQ()
					else:
						self.deleteMovieQ(selectedlist, self.remRecsToStop)

**Comment by dhwz** [comment]
[MovieSelection.zip](https://github.com/betonme/e2openplugin-EnhancedMovieCenter/files/1624218/MovieSelection.zip)

**Comment by svenh0** [comment]
mmh, so läuft es durch.
Wenn ich einen Timerfehler provoziere, kracht es in 2268 (out of range), vermutlich weil der Index sich verschiebt ;) 

				del self.deleteList[e[1]]

Und die Sicherheit würde ich auch noch reinmachen

if len(self.deleteList)>0:
			self.deleteMovieQ(self.deleteList, self.remRecsToStop)

**Comment by svenh0** [comment]
oder man sammelt alle Indexe und löscht zum Schluss in einem Rutsch

**Comment by dhwz** [comment]
Hm ja glaub es müsste heißen del self.deleteList[e[1]-i], pro Löschvorgang eins mehr abziehen als davor.

`	def stopRecordConfirmation(self, confirmed):
		if not confirmed: return
		# send as a list?
		stoppedAll=True
		filenames = "\n"
		i=0
		for e in self.recsToStop:
			stoppedResult = self["list"].recControl.stopRecording(e[0])
			stoppedAll = stoppedAll and stoppedResult
			if stoppedResult == False:
				filenames += "\n" + e[0].split("/")[-1][:-3]
				del self.deleteList[e[1]-i]
				i+=1
		if not stoppedAll:
			self.checkHideMiniTV_beforeFullscreen()
			self.session.open(MessageBox, _("Not all timers have been stopped. Modify them with the timer editor.") + filenames, MessageBox.TYPE_INFO, 10)
			if len(self.deleteList)>0:
				self.deleteMovieQ(self.deleteList, self.remRecsToStop)
		else:
			self.deleteMovieQ(self.deleteList, self.remRecsToStop)`

**Comment by dhwz** [comment]
Also bei mir haut es so hin, falls ich keinen Anwendungsfall übersehn hab.

**Comment by svenh0** [comment]
klappt perfekt, auch bei fehlerhaftem Beenden eines Timers.
Dabei (also mit Fehler beim Timer-Beenden) gibt es nur eine komische Sache.
Man sieht zuerst die Frage zum Löschen der übriggebliebenen Aufnahme.
Dahinter ist der Hinweis, das es beim Timer xxx ein Problem gab ;)

**Comment by dhwz** [comment]
hm ja kann, sein aber das ja egal solange der User die Info bekommt

**Comment by svenh0** [comment]
Ist ja wie gesagt nur ein Schönheitsmangel.
Von der Logik her müsste erst der Fehler kommen und dann die Frage zum Löschen der restlichen Aufnahmen.

Wären ja nur 3 Zeilen mehr, oder ?

**Comment by dhwz** [comment]
Ja kann aber sein dass er bei der MessageBox nicht wartet und den restlichen Code direkt ausführt.

**Comment by svenh0** [comment]
ich teste gerade mal

**Comment by svenh0** [comment]
so geht's ;) 
Ein zusätzliches CallBack (def deleteMovieQfirst) bei der Fehler-Info (nur, wenn auch noch was zu löschen ist).

	def stopRecordConfirmation(self, confirmed):
		if not confirmed: return
		# send as a list?
		stoppedAll=True
		filenames = "\n"
		i=0
		for e in self.recsToStop:
			stoppedResult = self["list"].recControl.stopRecording(e[0])
			stoppedAll = stoppedAll and stoppedResult
			if stoppedResult == False:
				filenames += "\n" + e[0].split("/")[-1][:-3]
				del self.deleteList[e[1]-i]
				i+=1
		if not stoppedAll:
			self.checkHideMiniTV_beforeFullscreen()
			if len(self.deleteList)>0:
				self.session.openWithCallback(self.deleteMovieQfirst, MessageBox, _("Not all timers have been stopped. Modify them with the timer editor.") + filenames, MessageBox.TYPE_INFO, 10)
			else:
				self.session.open(MessageBox, _("Not all timers have been stopped. Modify them with the timer editor.") + filenames, MessageBox.TYPE_INFO, 10)
		else:
			self.deleteMovieQ(self.deleteList, self.remRecsToStop)

	def deleteMovieQfirst(self, confirmed):
			self.deleteMovieQ(self.deleteList, self.remRecsToStop)

**Comment by dhwz** [comment]
Ok wart ich bau es mal ein ;)
Was soll eigentlich das dämliche self.checkHideMiniTV_beforeFullscreen() überall im Code ich glaub ich räum da mal auf...

**Comment by svenh0** [comment]
man könnte auch nur die CallBack-Info machen und das "if len(self.deleteList)>0:" erst in der CallBack-Funktion prüfen.

Das mit dem HideMiniTV sagt mir auch nichts.

```
def stopRecordConfirmation(self, confirmed):
	if not confirmed: return
	# send as a list?
	stoppedAll=True
	filenames = "\n"
	i=0
	for e in self.recsToStop:
		stoppedResult = self["list"].recControl.stopRecording(e[0])
		stoppedAll = stoppedAll and stoppedResult
		if stoppedResult == False:
			filenames += "\n" + e[0].split("/")[-1][:-3]
			del self.deleteList[e[1]-i]
			i+=1
	if not stoppedAll:
		self.checkHideMiniTV_beforeFullscreen()
		self.session.openWithCallback(self.deleteMovieQfirst, MessageBox, _("Not all timers have been stopped. Modify them with the timer editor.") + filenames, MessageBox.TYPE_INFO, 10)
	else:
		self.deleteMovieQ(self.deleteList, self.remRecsToStop)

def deleteMovieQfirst(self, confirmed):
	if len(self.deleteList)>0:
		self.deleteMovieQ(self.deleteList, self.remRecsToStop)
```

**Comment by dhwz** [comment]
Ja hatte ich schon so gemacht ;)

**Comment by dhwz** [comment]
Danke für deinen Support zu zweit klappt halt schneller, weil ich das hier auch nicht alles testen kann an meiner DevBox.

**Comment by svenh0** [comment]
Hier noch die miniTVHide...
Scheint auch nur für nicht-DreamOS zu sein !?!?

	def checkHideMiniTV_beforeFullscreen(self):
		if self.hide_miniTV and (config.EMC.hide_miniTV_method.value == "singlePixelMuted") and not isDreamOS:
			if not (config.EMC.movie_cover.value or config.EMC.movie_preview.value):
				self.session.nav.stopService() #even if EMC.hide_miniTV_method is singlePixelMuted
				self["Video"].hide()

**Comment by dhwz** [comment]
Ja aber ich finde das total gestört dass das überall im Code aufgerufen wird.

**Comment by svenh0** [comment]
Vor jeder Messagebox ???

**Comment by dhwz** [comment]
ja scheinbar ich versteh den Sinn dahinter nicht

**Comment by svenh0** [comment]
kann schon sein, dass die Messagebox sonst irgendwie hinter dem MiniTV ist oder so.
Scheint bei DreamOS ja nicht zu passieren ;)

**Comment by dream-alpha** [comment]
danke jungs... werde das morgen mal testen.

**Comment by dhwz** [comment]
@svenh0 
Wir haben da noch ein Problem die cuts werden nicht gelöscht wenn der Timer gestoppt und direkt die Aufnahme gelöscht wird weil die cuts erst kurz danach geschrieben wird.

**Comment by svenh0** [comment]
hmm mit cuts hab ich mich noch nicht beschäftigt. 
Wie viel später passiert das denn?

Evtl. könnte man das Löschen ein paar Millisekunden mit delay nach hinten verlegen. 
Wobei zwischen Timer beenden und Antwort zur Löschfrage ja auch schon einige Zeit verstreicht.

**Comment by dhwz** [comment]
Ich denke das wird von hier angestoßen.
DelayedFunction(3000, self.mergeCutListAfterRecording, filename)

**Comment by dhwz** [comment]
Also wenn man nicht 3 Sekunden wartet bevor man das Löschen bestätigt hat man dann immer diese Geister-Cuts im Verzeichnis liegen.

**Comment by svenh0** [comment]
Ok. Das ist ja dann schon immer passiert, wenn ich das Löschen innerhalb von 3 Sekunden bestätigt habe. 

Vielleicht kann man ja ne tempVariable setzen beim Timer beenden, dass diese mergecutlistafterrecording nur ausgeführt wird, wenn der Timer nicht manuell beendet wurde. 

Mir fehlt da noch die Codeübersicht ;)
Am Handy eher schlecht.

**Comment by dhwz** [comment]
Ich hab das mal umgebastelt, ich hab diese großen Delays mal verkürzt und dann warte ich bevor ich löschen auch eine kurze Zeit bis die Cuts geschrieben sind. Eigentlich sollte das nichts kaputt machen. Kannst ja mal testen wenn du wieder dran sitzt.

**Comment by svenh0** [comment]
> hat man dann immer diese Geister-Cuts im Verzeichnis liegen

meinst du die 0 Byte ...ts.ts.cuts ?? (also mit doppelt ts.)
Die habe ich auch bei ganz normalen Aufnahmen von gestern/heute, die ich nicht gelöscht habe.
Mit der Version von gestern bleiben nach dem Löschen von laufenden Aufnahmen nur diese 0 Byte ts.ts.cuts übrig.

Hab die aktuelle Version noch nicht installiert, laufen gerade Aufnahmen ;)
Aber wenn das mit dem neuen Delay passt, dann ist doch ok. Code-technisch sieht es ja gut aus.
Teste dann später mal, wenn die Box frei ist.

**Comment by svenh0** [comment]
Hab gerade eine freie Lücke der Box genutzt zum Update/Test.
Mit der aktuellen Version bleiben keine 0 Byte .cuts übrig. :)
Komischerweise sind jetzt die anderen von den gestrigen/heutigen Aufnahmen auch weg.
Werden die beim GUI-Neustart irgendwo bereinigt ?

**Comment by dhwz** [comment]
Ich wüsste nicht von wem oder wo, aber wer weiß :)
Dass diese ts.ts.cuts entstand sind war noch ein Bug, weil da irgendwer mal was geändert hatte an den Timerfilenames. Aber das ist jetzt ja auch korrekt. Aber wenn es bei dir auch klappt bin ich zufrieden, wieder ein Problem weniger :)

**Comment by svenh0** [comment]
Hab gerade festgestellt, dass das installierte AutomaticCleanup auch verweiste Filmdateien löscht, deshalb hatte ich wohl nie welche ;)
