### ISSUE TITLE
Starten von wiederholendem Timer einer laufenden Sendung erzeugt 2 Aufnahmen

### ISSUE THREAD

**Issue by dream-alpha** [betonme/e2openplugin-EnhancedMovieCenter#222]
folgender usecase:
- man geht ins epg und legt fuer die laufende sendung einen wiederholenden timer an, z.b. taeglich
- dann in die movieliste und findet eine abgeschlossene aufnahme der sendung von wenigen sekunden und eine laufende aufnahme... die, die man eigentlich haben will.
bitte beheben, danke.

**Comment by dhwz** [comment]
Sorry da bist du hier falsch

**Comment by svenh0** [comment]
Denke auch nicht, dass das ein Problem von EMC ist. 
Habe das aber gerade mal bei mir getestet. 
Ich habe dann im EMC nur eine Aufnahme für den laufenden Timer. 
Drücke doch im EMC mal die TV-Taste, wenn du die 2 Aufnahmen siehst. 
Ändert sich dann was ?

**Comment by dream-alpha** [comment]
ich sehe keine 2 laufende aufnahmen, sondern eine abgeschlossene von 5 sekunden oder so und eine laufende...und wenn ich die 5 sekunden aufnahme loesche, laeuft die regulaere normal weiter.

**Comment by dhwz** [comment]
Du hast jetzt aber nicht das dämliche Foldercaching im EMC aktiviert? Dafür bgeb ich keinen Support das Teil ist höchst experimentell.

**Comment by Swiss-MAD** [comment]
Folder caching müsste default immer noch aus sein oder?
Nur weil die letzte Zeit das ein paar eingeschaltet hatten. Das Funktionierte noch nie ganz sauber.

**Comment by dhwz** [comment]
Ja eigentlich schon wundert mich auch.

**Comment by dream-alpha** [comment]
was mir auch aufgefallen ist: wenn ich eine laufende aufnahme gleichzeitig abspielen will, dann spielt er manchmal (ist nicht einfach reproduzierbar) die darunterliegen aufnahme ab.

**Comment by dhwz** [comment]
Dann gilt wieder das vom Anfang hat nichts mit EMC zu tun.

**Comment by svenh0** [comment]
@dream-alpha 
Hast du mal die TV-Taste gedrückt, wenn du die doppelten Einträge siehst?
(also eine fertige Aufnahme und eine laufende)
Passiert da was ?

**Comment by dream-alpha** [comment]
hmm, irgendwie kann ich es gerade nicht reproduzieren :-(

**Comment by dhwz** [comment]
Ja klar weil das Problem nicht existiert. ;)

**Comment by dhwz** [comment]
aber @svenh0 ich bin auf der Suche nach einem anderen Problem vielleicht hast nee Idee
Neue Aufnahme starten, EMC macht nen reload, wenn du zu schnell EMC wieder aufrufst hast du dann einen leeren Bildschirm wegen 
EMC: [EMC] LOAD PATH:
/media/hdd/movie/20180113 1000 - RTL HD - Der Blaulicht Report.ts.ts

Der Pfad ist falsch das müsste /media/hdd/movie sein
Wartet man etwas länger (der Fehler kommt natürlich trotzdem im Log), dann lädt EMC natürlich den richtigen Pfad.

EMC: [EMC] LOAD PATH:
/media/hdd/movie

**Comment by dream-alpha** [comment]
doch das problem existiert... in meinem abfalleimer habe ich noch die beiden aufnahmen... eine mit 8 mb und die andere halt laenger... aber ja, ist kein emc problem.

**Comment by dhwz** [comment]
Wenn bei dir 2 Dateien existieren hast du ein größeres Problem weil das ist nicht normal und passiert eigentlich auch nicht. Mit einem Standardimage passiert das definitiv NICHT.

**Comment by dhwz** [comment]
@svenh0 
Ich weiß schon wo das passiert...
DelayedFunction(3000, self.globalReload, filename)

**Comment by svenh0** [comment]
Bin gerade unterwegs. Komme erst Abend dazu, mich damit zu beschäftigen ;)

**Comment by svenh0** [comment]
Und wenn man bei reload auf den Pfad reduziert?
Wieso wird da überhaupt der filename übergeben. 

Wie schnell muss ich EMC nach Aufnahmestart öffnen, um das Problem zu haben?

Bin noch unterwegs ;)

**Comment by dhwz** [comment]
Glaub mit dem anderen Fix um die cuts zu löschen hab ich das jetzt auch behoben, man müsste das EMC jetzt schon innerhalb von 500ms aufrufen damit man da noch einen doppelten Eintrag erhält, ich denke das mit dem Filename wird gemacht damit die Liste (falls sie mal etwas größer ist) nicht komplett neu geladen werden muss sondern nur um den Eintrag für die Aufnahme ergänzt.

Wie gesagt mit dem Delay ist das jetzt mehr oder weniger weg, bzw. passiert nur noch wenn man schneller als 500ms wäre, da müsste man dann höchstens noch einen Check einbauen ob der Eintrag in der Liste schon enthalten ist, sonst hat man wieder das Duplikat drin.

**Comment by svenh0** [comment]
hmm, hab gerade nochmal die alte Version getestet.
Auch wenn ich nach Aufnahmestart blitzschnell das EMC aufgerufen habe (unter 3 Sekunden), hatte ich keine doppelten Einträge.
Mit der neuen Version erst recht nicht ;)
Egal, nun sollte es passen.

Hoffentlich gibt es wegen dem kurzen Delay jetzt kein Problem bei anderen Boxen.
Muss sich damals ja einer was dabei gedacht haben wegen den 3 Sekunden ;)

**Comment by dhwz** [comment]
Ja, wobei ich keine logische Erklärung dafür hab warum man da 3 Sekunden warten müsste. Aber schauen wir mal ob sich wer meldet. ;)
