### ISSUE TITLE
Setup "Move finished movies in trashcan" -> Crash

### ISSUE THREAD

**Issue by Swiss-MAD** [betonme/e2openplugin-EnhancedMovieCenter#224]
Im Setup beim Punkt "Move finished movies in trashcan" kommt anschliessend noch eine Sicherheitsabfrage für diese Funktion. Das bestätigen dieser führt zum Crash.

`Traceback (most recent call last):
  File "/usr/lib/enigma2/python/enigma.py", line 7790, in __call__
    return ret(*args, **kwargs)
  File "/usr/lib/enigma2/python/Components/ActionMap.py", line 51, in action
    res = self.actions[action]()
  File "/usr/lib/enigma2/python/Plugins/Extensions/EnhancedMovieCenter/plugin.py", line 114, in cancel
    self.closeConfirmBox(False)
  File "/usr/lib/enigma2/python/Plugins/Extensions/EnhancedMovieCenter/plugin.py", line 117, in closeConfirmBox
    eActionMap.getInstance().unbindAction('', self.action)
AttributeError: 'eActionMap' object has no attribute 'unbindAction'`

**Comment by svenh0** [comment]
Müsste hier nicht "self.close(False)" hin ?
https://github.com/betonme/e2openplugin-EnhancedMovieCenter/blob/3fd66b97b5bd647a71eed5c531d1e9605b45039e/src/plugin.py#L114

**Comment by dhwz** [comment]
Ich versteh den Sinn des kompletten Codeabschnittes nicht das ist doch gar nicht nötig was da gemacht wird.

**Comment by dhwz** [comment]
Ich werd den bind/unbind Unsinn da mal raus es reicht doch völlig aus wenn man die 2 Farbtasten nacheinander drückt, da muss doch nicht nochmal jede andere Taste den Vorgang unnötig zurücksetzen.

**Comment by dhwz** [comment]
https://github.com/betonme/e2openplugin-EnhancedMovieCenter/commit/1172f3dae38639e3554551ecf36aaca5ab20c94d
