### ISSUE TITLE
2 movie dirs

### ISSUE THREAD

**Issue by dream-alpha** [betonme/e2openplugin-EnhancedMovieCenter#225]
hab da noch ne kleinigkeit: 2 movie dirs in der liste. wenn man auf die obere clickt springt er zum papierkorb, bei der unteren keine reaktion.
hab 2 platten drin eine interne und eine usb. vielleicht kommt es daher.

![screenshot - edited](https://user-images.githubusercontent.com/35299421/35194635-a591bc18-feb6-11e7-90f6-bc866f321d8a.jpg)

**Comment by Swiss-MAD** [comment]
Hast du mal etwas mehr Infos ?
Weshalb hast du 2 x das Verzeichnis movie ? Auf welchem Pfad befindest du dich ? (MovieHome)
Hast du da Symlinks auf die einzelnen Platten, auf das Verzeichnis movie ?
Hat es nach einem Realod immer noch 2x movie ?
Hast du die Verzeichnis-Cache Option in EMC aktiviert ? Die ist buggy.

**Comment by Swiss-MAD** [comment]
Wenn das 2 Symlinks sind die auf /media/hdd/movie und /media/usb/movie zeigen, dann wird wohl beim Klick auf den der auf /media/hdd/movie zeigt einfach das Verzeichnis eingelesen (was dann in dem Fall einfach wieder dasselbe ist aber) und der Cursor springt an den Anfang so wie wenn du das Verzeichnis wechselst.
Wenn der 2. Symlink stimmt, solltest du aber eigentlich in /media/usb/movie landen. Ist das nicht so ?
Ansonsten mal mitloggen.

**Comment by dream-alpha** [comment]
ja, stimmt. so ist es. ich habe jetzt die e2 und emc symlinks in den settings ausgeschaltet. damit sind die dirs weg. danke. ich mache zu.

**Comment by Swiss-MAD** [comment]
E2 und EMC ? Dann hattest du aber Bookmarks und keine Symlinks.
Passiert aber am Ende dasselbe egal ob Bookmark oder Symlink. ;)

**Comment by dream-alpha** [comment]
ja, das waren wohl bookmarks, wobei mir die geschichte mit symlinks, bookmarks und das handling noch nicht so ganz klar ist.
was mich verwirrt hat war, dass ich im movie dir 2 eintraege auf movie dir habe und zwar nur bei der internen platte. bei der usb-platte sind keine 2 movie dirs. deswegen dachte ich, dass das ein bug sein muss. 
aber da ich jetzt einen weg gefunden habe, die eintraege zu eliminieren, ist alles gut, :-)

**Comment by Swiss-MAD** [comment]
Ja EMC macht da überhaupt nichts.
Wenn du keine Bookmarks oder symlinks erstellst erscheint da auch nichts.
Ein symlink ist ja eine Verknüpfung im Dateisystem, EMC listet das auf wie jedes andere Verzeichnis / Datei.
Bookmarks legst du selbst an, und die kann man nach Wunsch ein oder ausblenden. Wenn icons eingeschaltet ist, siehst du auch was es ist.
Es steht also jedem frei, ob er auf jeder platte eine symlink auf die andere platte zum schnellen hin und her wechseln möchte.
Bookmarks erscheinen aber natürlich immer alle im Movie Home.
Das kann sich also jeder genau nach seinen wünschen einrichten.

**Comment by dream-alpha** [comment]
mit symlinks meinst du dann die ln -s ... links, richtig?
die moechte ich eigentlich vermeiden, weil die ja nicht von enigma2 "verwaltet" sondern manuell auf linux-ebene bei aenderungen angepasst werden muessen.
von daher ist die bookmark-geschichte ja nicht schlecht... aber wenn die nur auf der movie home platte angezeigt werden, ist es imho suboptimal.

**Comment by Swiss-MAD** [comment]
Ja der Symbolische Link ist das mit "ln -s"
Aber ich weiss nicht was du für eine Abneigung davon hast, ich finde das eine tolle Sache, zudem kannst du dir die ja sogar von EMC im Menü erstellen lassen ohne einen Buchstaben Tippen zu müssen ;)
Ein Symlink kann auch überall sein oder mehrere auf das selbe Ziel zeigen.

Bookmarks überall anzeigen zu lassen wäre zu unübersichtlich, zudem kann du die ja auch direkt in EMC aufrufen (z.b. auf eine Farbtaste legen).

Viele haben oft verwendete Pfade als E2 Bookmark abgelegt, weil man die dann beim erstellen eines Timer direkt mit den Pfeiltasten aufrufen kann.
So viele Bookmarks würden aber im MovieHome stören.
Deshalb haben wir auch noch EMC eigene Bookmarks angelegt, die man nur dazu verwendet kann von MovieHome aus direkt irgend welche Ziele an zu steuern.
Möchtest du von einem Pfad der nicht MovieHome ist direkt wo anders hin gelangen, ist wieder der Symoblische Link dein Freund. ;)
Mit diesen Hilfsmitteln kannst du dir alles so einrichten wie du es gerne hättest, solange du dich nicht prinzipiell gegene eine Funktion/Möglichkeit weigerst.  :wink:

**Comment by dream-alpha** [comment]
danke fuer die erklaerung. fuer meinen einfachen anwendungsfall reichen zwei e2 bookmarks fuer die beiden platten ... und damit sie mich nicht im movie home stoeren, hab ich sie ausgeblendet.
von daher ist das fuer mich so ok. ;-)

**Comment by Swiss-MAD** [comment]
Für deinen Anwendungsfall würde ich es persönlich so machen:
Int. HDD als MovieHome festlegen und MovieHome auf eine Farbtaste legen. (Oder einfach die Taste 0 verwenden, die ist immer MovieHome  :relaxed:)
Auf der Int. Platte einen Symlink (oder EMC Bookmark) auf die USB-Platte legen. (alle anderen EMC Bookmarks löschen damit du nur diesen einen Eintrag hast.)

So kannst du mit diesem einen Bookmark oder Symlink direkt auf die USB Platte zugreifen, und mit der MovieHome Taste (oder 0) auch direkt wieder zurück auf die Int. Platte.  :sunglasses:

**Comment by dream-alpha** [comment]
auch ne moeglichkeit....
