### ISSUE TITLE
Hang beim Loeschen einer laufenden Aufnahme

### ISSUE THREAD

**Issue by dream-alpha** [betonme/e2openplugin-EnhancedMovieCenter#230]
folgendes problem: schaue eine laufende aufnahme mit wiederholendem timer.
stoppe die wiedergabe, selektier rot zum loeschen, ja loesche aufnahme, ja beende timer.
gehe zur senderliste und will umschalten... zahnraedchen und nix geht mehr.
gehe in ne telnet session: systemctl stop enigma2... haengt, reboot... nix... haengt.
lasse die box ne weile haengen... ploetzlich... nach minuten hat sie umgeschaltet und die aufnahme laeuft weiter.
loesche die aufnahme nochmal... und dieses mal funktioniert es problemlos.
irgendein timing problem?

**Comment by dhwz** [comment]
Auf jeden Fall kein Thema von EMC, bitte nicht jedesmal ein Issue öffnen sondern erstmal logisch nachdenken ob das überhaupt hier rein passt.

**Comment by dream-alpha** [comment]
verstehe nicht, warum das kein emc problem sein kann.
