### ISSUE TITLE
EMC as standard player in openwebif?

### ISSUE THREAD

**Issue by chrisoutwright** [betonme/e2openplugin-EnhancedMovieCenter#233]
Is it possible to choose EMC as standard player as executable to the ajax implemented function `playRecording(sRef)` as defined in `/js/openwebif.js` ?

I am using Alexa Echo and would like to use voice commands, yet fiddling directly with .py files in the extensions folder seems to fail me, although I have taken a look in the E2 folder `/plugin/controllers/web.py`, see [Link](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/275930de919054e5a964c6e11127e8c1a596905a/plugin/controllers/web.py). 
Would it be possible to have the most important functions usable in openwebif, instead of creating a separate web.py for EMC?

**Comment by hirenshah** [comment]
Any reason why this was just closed?
