### ISSUE TITLE
preparePlayback not initialized

### ISSUE THREAD

**Issue by dream-alpha** [betonme/e2openplugin-EnhancedMovieCenter#241]
variable preparePlayback ist in zeile 2931 in MovieCenter.py nicht initialisiert.

toggleProgressService(service, **preparePlayback**)

**Comment by dream-alpha** [comment]
also hier komme ich nicht drauf, wodurch das preparePlayback gesetzt wird.
es kann natuerlich sein, dass python irgendeinen default wert annimmt, der zufaellig passt... aber schoen waere das nicht.

**Comment by dhwz** [comment]
Hast du einen Crash dann häng das Log an ;)

**Comment by dream-alpha** [comment]
der crash passiert nur in meinem kopf. (aber das wundert euch ja sicher nicht ;-))

**Comment by svenh0** [comment]
Jagst du den Plugin-Code durch einen Code-Checker? :) 

Wie kommt nan denn sonst auf solche Fundstellen?
Das merkt man doch eigentlich nur bei einem Crash im Plugin.

**Comment by dream-alpha** [comment]
yep, pyflakes... das meiste ist ja unkritisch... aber an dieser stelle koennte es ein bug sein.
