### ISSUE TITLE
Import for TryQuitMainloop missing in EMCTasker.py

### ISSUE THREAD

**Issue by dream-alpha** [betonme/e2openplugin-EnhancedMovieCenter#242]
.

**Comment by dhwz** [comment]
hast du irgendwie langeweile?!?

**Comment by Swiss-MAD** [comment]
@dream-alpha 
Würdest du bitte dazu schreiben was genau das Problem und was du damit willst ?
So macht das doch keinen Sinn?

**Comment by dream-alpha** [comment]
ein programmierer versteht das auch ohne lange erklaerung (wenn er denn will)

**Comment by dhwz** [comment]
entweder du machst es richtig oder du lässt das spammen hier einfach sein, ich besseres zu tun als mir das hier anzuschauen...

**Comment by Swiss-MAD** [comment]
@alpha
Ich sehen schon das wir TryQuitMainloop unter Umständen einmal aufrufen den am Anfang aber nicht importieren. Na und ?

**Comment by dream-alpha** [comment]
ohne import laeuft da nix... aber ich denke, es wird von  "from Screens.Standby import *" mitimportiert.
bei stern sieht man halt nicht, was alles importiert wird.

**Comment by dhwz** [comment]
Siehst und genau darum geht es du meldest Fehler ohne zu belegen (Log) dass überhaupt ein Problem besteht.

**Comment by Swiss-MAD** [comment]
@dream-alpha 
Schön das du dir nun die Gedanken gemacht hast, die du von Anfang an hättest machen sollen ;)

**Comment by dream-alpha** [comment]
ihr seid so gut zu mir ;-)
