### ISSUE TITLE
VU+ VTI 13.x Skincrash beim umbenennen

### ISSUE THREAD

**Issue by Dieter59** [betonme/e2openplugin-EnhancedMovieCenter#243]
ist im VU+ Forum hier beschrieben:
[https://www.vuplus-support.org/wbb4/index.php?thread/83810-iflatfhd-anpassungen-modifications-colors-fonts-skinparts/&postID=1747622#post1747622](url)
Es gibt eine neues widget „configdesc“ Gordon55 hat die Lösungen zwei Posts weiter beschrieben

**Comment by Swiss-MAD** [comment]
Die Lösung für VTI ?
Wir können doch nicht für jedes Fremdimage Speziallösungen machen.
Wenn wir jedes mal unsere ScreenNamen ändern würden, hätten bestimmt alle Skinner die die Teile von EMC geskinnt habe eine Freude das sie wieder was ändern dürfen. Dieser ScreenNamen gibt es schon eine halbe Ewigkeit in EMC.
VTI könnte doch auch seinen Skinnamen ändern um unabhängig von Plugins zu sein, anstelle wie Gordon schreibt das wir anpassen um unabhängig vom Image zu sein. Referenz für uns ist DreamOS.

**Comment by atvcaptain** [comment]
vti ist ein close image also kein support
