### ISSUE TITLE
Formatting texts

### ISSUE THREAD

**Issue by alec-cs** [betonme/e2openplugin-EnhancedMovieCenter#244]
I would like to solve the following (look at the attached picture):

1.) I want to format this: 1 hour 58 min (instead of 118 min)

I think so:
There would be a global function that would return the text you want to print (back hours and minutes only):

- - - 
def hour_min(mins):
  if not isinstance(mins, int):
    return '0 _("time_min")'
    
  if mins <= 0:
    return '0 _("time_min")'
    
  vhour, vmins = mins // 60, mins % 60
    
  if vhour and vmins:
    return '{0} _("time_hour") {1} _("time_min")'.format(vhour, vmins)
  elif vhour and not vmins:
    return '{0} _("time_hour")'.format(vhour)
  else:
    return '{0} _("time_min")'.format(vmins)
- - - 

The "time_hour", "time_min" should be loaded into a .pot file (I want to format).

2.)  Put it in the .pot file so that it can be formatted. 
     
I would like to format: 2018, April 30. - Monday    (Year, Mounth Day. - Name of day)

- - - - - 

openATV 6.1 is my system.

I hope You understand what I want.

Please solve it.

Thanks in advance.

Alec

![picture1](https://user-images.githubusercontent.com/1958093/40672496-475c6ca6-636f-11e8-81bd-f39e68244784.jpg)

**Comment by dhwz** [comment]
These are no Plugin issues
1. Is already working see original Skin
2. Is job of your image
