### ISSUE TITLE
#TODOret

### ISSUE THREAD

**Issue by dream-alpha** [betonme/e2openplugin-EnhancedMovieCenter#249]
was bedeuten denn eigentlich die kommentare #TODOret?
was fehlt da und warum braucht man es? laeuft ja auch anscheinend ohne.

**Comment by dhwz** [comment]
?

**Comment by Swiss-MAD** [comment]
Wieso stellst du solche Fragen nicht einfach im Forum ?
Die Issues hier sind doch nicht dafür gedacht.

**Comment by dream-alpha** [comment]
weil ich die frage direkt an die codierer adressieren wollte.

**Comment by dhwz** [comment]
Und das soll hier dann was genau bringen, dir ist schon klar dass der meiste Code von Leuten stammt die sich damit schon längst nicht mehr beschäftigen, bzw. gar nicht mehr aktiv sind?
Außerdem scheinst echt Langeweile zu haben wegen solcher Lappalien hier ein Issue aufzumachen, kann dir ja eigentlich egal sein ob da irgenwelche Kommentare im Code stehn. Und wie Swiss-MAD schon sagte im offiziellen Supporthread hätte man auch fragen können.

**Comment by dream-alpha** [comment]
ist ja nicht schlimm, wenn es keiner weiss.
todo bedeutet halt, das da irgendwas fehlt... sonst haette es derjenige ja nicht hingeschrieben.

**Comment by betonme** [comment]
Ich löse das mal auf.

Vor Jahren hatte ich an der Stelle Probleme mit dem return Wert.

Die Kommentare habe ich dann wohl übersehen, können gerne entfernt werden.

**Comment by dhwz** [comment]
@betonme 
Ok :)
