### ISSUE TITLE
Incorrect special characters for Czech and Slovak long texts

### ISSUE THREAD

**Issue by juraj1000** [betonme/e2openplugin-EnhancedMovieCenter#254]
Hello,
I've just implemented the latest update of enigma2-plugin-extensions-enhancedmoviecenter_4.0+git1582+20181231_all, I use DM500HD with Open PLi. 
There is a new issue with Czech and Slovak special characters in "long" texts for detail description of recordings. The special CZ/SK characters are incorrectly displayed in EMC screen. And if I press the button Info in EMC there is the same issue with incorrect CZ/SK special characters.
But if I press the button Info in the skin (not in EMC) the same "long" text for detail description is displayed with correct CZ/SK special characters, there is not any issue with it.
It seems that EMC doesn't know correctly implement special characters for long texts even when the skin can interpret it correctly.
I think that EMC knew interpret correctly special characters in older release.
Could you correct it please?
Juraj

**Comment by dhwz** [comment]
There are NO special CZ/SK characters, get your Image fixed as this is not an EMC issue. EMC is behaving properly and decoding any code page.
