### ISSUE TITLE
Major Problem with Enhanced Movie Center

### ISSUE THREAD

**Issue by ozone1864** [betonme/e2openplugin-EnhancedMovieCenter#269]
Dears,
Please note that the following problem which will be state is not found in the old movie center, it is being faced only in the enhanced movie center.
The problem is whenever you watch a movie it should save a progress in the bar, but some players don't work with cuts files, they have their own save and resume way without cuts files.
The old movie center still get the progress bar and resume function without cuts files, why this function was removed in the enhanced movie center ?
Thanks with best regards,

**Comment by ozone1864** [comment]
@dhwz ??????????????????

**Comment by Swiss-MAD** [comment]
There was never a "old" movie center.
All E2 (DreamOS) player works with .cuts files.
Where will you store the position without a .cuts file?

**Comment by ozone1864** [comment]
> There was never a "old" movie center.
> All E2 (DreamOS) player works with .cuts files.
> Where do you will store the position without a .cuts file?

First:
It is called movielist in openPLI or openATV, and in other images movie center.
Using Zgemma H9S which is not based on broadcom chip, but instead based the service hisilicon.
Service hisilicon doesn't use cuts files for mp4 or mkv to save progress

**Comment by ozone1864** [comment]
I noticed when watching .mkv movie and stopping it for example it doesnt save .cuts file
but movielist still knows the progress time.
Enhanced movie center doesn't

**Comment by ozone1864** [comment]
Please try to find solution for this issue since I keep using enhanced movie center.
Movielist is very old

**Comment by Swiss-MAD** [comment]
EMC was always made for Dreamboxes and theirs Images.
I have never used a Open**** image.
I think "Movielist" is a own plugin from the Open**** image or a modificated Movielist from a very very old dreambox image.
On dreamboxes EMC works very well.

**Comment by ozone1864** [comment]
> EMC was always made for Dreamboxes and theirs Images.
> I have never used a Open**** image.
> I think "Movielist" is a own plugin from the Open**** image or a modificated Movielist from a very very old dreambox image.
> On dreamboxes EMC works very well.

When u install openATV it comes equipped with EMC no need to go and install it.
If we remove it, the old movielist will comeup.
If you can just compare movielist with EMC about progress save without cuts. I would appreciate
and if you want I can try finding the solution out and reporting it back to you for fix ?

**Comment by Swiss-MAD** [comment]
OpenATV never asked me for a permission to share EMC with their Image.
But now EMC it's open source and everyone can use it.
I hope the always changing EMC programmers (except me, I was one of the EMC founder) have a focus that EMC in first time running clean on Dreamboxes.

When it's need changes to run clean on OpenATV, everyone be free to make a fork from EMC with his special changes.

**Comment by ozone1864** [comment]
> OpenATV never asked me for a permission to share EMC with their Image.
> But now EMC it's open source and everyone can use it.
> I hope the always changing EMC programmers (except me, I was one of the EMC founder) have a focus that EMC in first time running clean on Dreamboxes.
> 
> When it's need changes to run clean on OpenATV, everyone be free to make a fork from EMC with his special changes.

Ah ok mate, so you want me to forward this to @atvcaptain  ?

**Comment by dhwz** [comment]
That means there will be no modifications for OpenATV on this repository. If someone is willing to change anything related to foreign images they can fork.
