### ISSUE TITLE
Settings file EMC 4 git 20200513

### ISSUE THREAD

**Issue by tommiedepommie** [betonme/e2openplugin-EnhancedMovieCenter#280]
Hello,

I have two receivers with Pure2 6.5 image. Both have emc4 20200513 installed.
On the ZgemmaH7S I can see the recordinglist WITH the statusbar howfar a recording is played.
Om the Gigablue 4K the same version but there is no bar visible.
The recordings are on a nas.
Is it a setting to display the progression bar or can I reset the complete settings on the Gigablue?
Removing and reinstalling the EMC doesn't solve the problem.

Thank you very much,

tom

**Comment by Swiss-MAD** [comment]
EMC is built and tested only for Dreamboxes, i don't now what is different on your Receivers.
EMC has no option to hide the Infobar, but when your Skin has incorrect EMC screen's, it's possible that you don's see a Infobar.
