### ISSUE TITLE
enigma2-plugin-extensions-enhancedmoviecenter 20210724+git0+8d81d42936-r0.0 missing dependencies

### ISSUE THREAD

**Issue by gracefulemail** [betonme/e2openplugin-EnhancedMovieCenter#284]
Hello, I have got dreambox DM 920, the plugin enigma2-plugin-extensions-enhancedmoviecenter 20210724+git0+8d81d42936-r0.0 does not work when I installed enigma2-plugin-extensions-enhancedmoviecenter via BP/Addon-Manager. The reason is there are missing dependencies on  python-mutagen,  python-requests packages that are not installed automatically. It started to work after I installed these two python packages manually. Such issue was not there in previous versions.

Regards,

Roman

**Comment by dhwz** [comment]
It was never on the feed before. It was added first time in the last update DP released.
We have nothing to do with that package, means we cannot fix that. But I'll send them a note.
