### ISSUE TITLE
Suggestion: add other activation keys (buttons)

### ISSUE THREAD

**Issue by Alexwilmac** [betonme/e2openplugin-EnhancedMovieCenter#291]
EMC is great but there is a problem: you can only choose to recall it by 3 keys: TV, Radio or F1 (which is not present in most of RC) and this creates some problems, for instance, to switch from TV bouquets to Radio ones and viceversa.

Would it be possible to have more keys to choose?
Because this way we can't even take advantage (under open images) to use the customization of keys to switch to RADIO, because if we assign "Switch to RADIO" to any keys, EMC interferes, either if we assign it to Radio button or to TV button (whilst many RC don't have any F1, as said).
°°°°°°°°°°°°°°°°°°°
I also thought to solve in an opposite way, assigning EMC to another key by the image's key customization, but you find only "EMC Setup" among the functions you can assign, not EMC GUI itself.

Thanks and regards.

**Comment by dhwz** [comment]
There are already 5 buttons + a don't do anything
