### ISSUE TITLE
Feature Request: Multi-select movies

### ISSUE THREAD

**Issue by wedebe** [betonme/e2openplugin-EnhancedMovieCenter#294]
Currently have to wait for each movie to be deleted individually then for the movie list to be refreshed.

It would be great to see a `Multiple select` mode, to facilitate more efficient deletion and move to folder.

**Comment by Swiss-MAD** [comment]
Use PVR key to mark movies in the movielist, after that use the delete button.
You can also mark from/to with the TEXT key.
