### ISSUE TITLE
EPG search over EMC submit always a SPACE character at the end of the movie name.

### ISSUE THREAD

**Issue by Swiss-MAD** [betonme/e2openplugin-EnhancedMovieCenter#60]
EPG search over EMC (Key [AUDIO / ...search EPG] when EPG search installed) submit always a SPACE character at the end of the movie name.

Therefore the search go's mostly wrong.

E2 Log example

EMC: lookup for events with 'Transporter - Die Serie ' in title(ignore case)
E2 MovieList: lookup for events with 'Transporter - Die Serie' in title(ignore case)

(The same, when you will add a autotimer over a EMC entry.)

**Comment by dhwz** [comment]
I think this is no longer valid
