### ISSUE TITLE
Remaining time not displayed on LCD during playback on Vu+ UNO

### ISSUE THREAD

**Issue by Misenkooo** [betonme/e2openplugin-EnhancedMovieCenter#71]
I have Vu+ Uno with one line LCD display. I've encountered one issue during movie playback with this plugin enabled though. LCD display does not show elapsed and remaining time of a video. Instead, last item from menu is displayed all the time, or sometimes a message "Resuming playback" is displayed. Without the plugin enabled, those times are displayed correctly. Could somebody please try to look at this issue?

**Comment by dhwz** [comment]
Just needs to bei skinned properly.
