### ISSUE TITLE
crash with external HDD to wake up

### ISSUE THREAD

**Issue by ulfito** [betonme/e2openplugin-EnhancedMovieCenter#81]
I have in my /movie dir a directoy /EXTERN
In /EXTEN are two symlinks: /NAS => Qnap TS219
                      /ESATA => extenal HDD on NAS

If extenal HDD on NAS sleeps and I navigate to it with emc..it crashes.
![crash](https://f.cloud.github.com/assets/4946677/752576/c70aa54c-e54a-11e2-8bc3-f38e41e62cc1.png)

if you need logfiles..i can post!

**Comment by Fischreiher** [comment]
Added a fix for a similar issue:
https://github.com/betonme/e2openplugin-EnhancedMovieCenter/commit/af0023446c96f1f8e203efadbe0acba84f8e3995
